/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Communication

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

// N1N2MessageUnSubscribe - Namf_Communication N1N2 Message UnSubscribe (UE Specific) service Operation
func N1N2MessageUnSubscribe(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
