/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Communication

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

// CreateUEContext - Namf_Communication CreateUEContext service Operation
func CreateUEContext(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// EBIAssignment - Namf_Communication EBI Assignment service Operation
func EBIAssignment(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RegistrationStatusUpdate - Namf_Communication RegistrationStatusUpdate service Operation
func RegistrationStatusUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReleaseUEContext - Namf_Communication ReleaseUEContext service Operation
func ReleaseUEContext(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UEContextTransfer - Namf_Communication UEContextTransfer service Operation
func UEContextTransfer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
