/*
 * 5G-EIR Equipment Identity Check
 *
 * 5G-EIR Equipment Identity Check Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.2.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "gogc/src/5geir/EquipmentIdentityCheck/handler"
	"gogc/src/5geir/EquipmentIdentityCheck/scenario"
	"log"
	"os"
)

func main() {
	log.Printf("Server started")

	// Init
	scenario.Init()
	router := sw.NewRouter()

	port := os.Getenv("ENV_5GEIR_EQUIPMENTIDENTITYCHECK")
	if port == "" {
		port = "8081"
	}
	port = ":" + port

	log.Fatal(router.Run(port))
}
