/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeletePcEventExposureSubsc - Cancels an existing Individual Policy Control Events Subscription 
func DeletePcEventExposureSubsc(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPcEventExposureSubsc - Reads an existing Individual Policy Control Events Subscription
func GetPcEventExposureSubsc(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PutPcEventExposureSubsc - Modifies an existing Individual Policy Control Events Subscription 
func PutPcEventExposureSubsc(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
