/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// NSSAIAvailabilitySubModifyPatch - updates an already existing NSSAI availability notification subscription
func NSSAIAvailabilitySubModifyPatch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NSSAIAvailabilityUnsubscribe - Deletes an already existing NSSAI availability notification subscription
func NSSAIAvailabilityUnsubscribe(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
