/*
 * Namf_MBSBroadcast
 *
 * AMF MBSBroadcast Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ContextDelete - Namf_MBSBroadcast ContextDelete service Operation
func ContextDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ContextUpdate - Namf_MBSBroadcast ContextUpdate service Operation
func ContextUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
