/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "gogc/src/udr/DataRepository/handler"
	"gogc/src/udr/DataRepository/scenario"
	"log"
	"os"
)

func main() {
	log.Printf("Server started")

	// Init
	scenario.Init()
	router := sw.NewRouter()

	port := os.Getenv("ENV_UDR_DATAREPOSITORY_PORT")
	if port == "" {
		port = "8481"
	}
	port = ":" + port

	log.Fatal(router.Run(port))
}
