/*
 * Npcf_AMPolicyAuthorization Service API
 *
 * PCF Access and Mobility Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteAmEventsSubsc - deletes the AM Policy Events Subscription subresource
func DeleteAmEventsSubsc(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateAmEventsSubsc - creates or modifies an AM Policy Events Subscription subresource.
func UpdateAmEventsSubsc(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
