/*
 * Namf_MT
 *
 * AMF Mobile Terminated Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.3
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// UeContextInfoClass - Indicates the UE Context information class
type UeContextInfoClass struct {
}
