/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ScpDomainRoutingInfoNotification - SCP Domain Routing Information Notification
type ScpDomainRoutingInfoNotification struct {

	RoutingInfo ScpDomainRoutingInformation `json:"routingInfo"`

	LocalInd bool `json:"localInd,omitempty"`
}
