/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// SnssaiRouteSelectionDescriptor - Contains the route selector parameters (DNNs, PDU session types, SSC modes and ATSSS information) per SNSSAI
type SnssaiRouteSelectionDescriptor struct {
	Snssai Snssai `json:"snssai"`

	DnnRouteSelDescs []DnnRouteSelectionDescriptor `json:"dnnRouteSelDescs,omitempty"`
}
