/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type MaReleaseIndicationAnyOf string

// List of MaReleaseIndicationAnyOf
const (
	_3_GPP MaReleaseIndicationAnyOf = "REL_MAPDU_OVER_3GPP"
	N3_GPP MaReleaseIndicationAnyOf = "REL_MAPDU_OVER_N3GPP"
)
