/*
 * 5G-EIR Equipment Identity Check
 *
 * 5G-EIR Equipment Identity Check Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.2
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model
// EquipmentStatus : Represents equipment status of the PEI. This data type is a string.
type EquipmentStatus string

// List of EquipmentStatus
const (
	WHITELISTED EquipmentStatus = "WHITELISTED"
	BLACKLISTED EquipmentStatus = "BLACKLISTED"
	GREYLISTED EquipmentStatus = "GREYLISTED"
)
