/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// PcfInfo - Information of a PCF NF Instance
type PcfInfo struct {

	// Identifier of a group of NFs.
	GroupId string `json:"groupId,omitempty"`

	DnnList []string `json:"dnnList,omitempty"`

	SupiRanges []SupiRange `json:"supiRanges,omitempty"`

	GpsiRanges []IdentityRange `json:"gpsiRanges,omitempty"`

	// Fully Qualified Domain Name
	RxDiamHost string `json:"rxDiamHost,omitempty"`

	// Fully Qualified Domain Name
	RxDiamRealm string `json:"rxDiamRealm,omitempty"`

	V2xSupportInd bool `json:"v2xSupportInd,omitempty"`

	ProseSupportInd bool `json:"proseSupportInd,omitempty"`

	ProseCapability ProSeCapability `json:"proseCapability,omitempty"`

	V2xCapability V2xCapability `json:"v2xCapability,omitempty"`
}
