/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ApplicationDataChangeNotif - Contains changed application data for which notification was requested.
type ApplicationDataChangeNotif struct {

	IptvConfigData IptvConfigData `json:"iptvConfigData,omitempty"`

	PfdData PfdChangeNotification `json:"pfdData,omitempty"`

	BdtPolicyData BdtPolicyData `json:"bdtPolicyData,omitempty"`

	// String providing an URI formatted according to RFC 3986
	ResUri string `json:"resUri"`

	SerParamData ServiceParameterData `json:"serParamData,omitempty"`

	AmInfluData AmInfluData `json:"amInfluData,omitempty"`
}
