/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type PlmnRestriction struct {

	RatRestrictions []RatType `json:"ratRestrictions,omitempty"`

	ForbiddenAreas []Area `json:"forbiddenAreas,omitempty"`

	ServiceAreaRestriction ServiceAreaRestriction `json:"serviceAreaRestriction,omitempty"`

	CoreNetworkTypeRestrictions []CoreNetworkType `json:"coreNetworkTypeRestrictions,omitempty"`

	PrimaryRatRestrictions []RatType `json:"primaryRatRestrictions,omitempty"`

	SecondaryRatRestrictions []RatType `json:"secondaryRatRestrictions,omitempty"`
}
