/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type CommunicationCharacteristicsAf struct {
	PpDlPacketCount *int32 `json:"ppDlPacketCount,omitempty"`

	// indicating a time in seconds.
	MaximumResponseTime int32 `json:"maximumResponseTime,omitempty"`

	// indicating a time in seconds.
	MaximumLatency int32 `json:"maximumLatency,omitempty"`
}
