/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// StatusInfo - Status of SM context or of PDU session
type StatusInfo struct {

	ResourceStatus ResourceStatus `json:"resourceStatus"`

	Cause Cause `json:"cause,omitempty"`

	CnAssistedRanPara CnAssistedRanPara `json:"cnAssistedRanPara,omitempty"`

	AnType AccessType `json:"anType,omitempty"`
}
