/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AccessTypeRm - Indicates wether the access is via 3GPP or via non-3GPP but with the OpenAPI 'nullable: true' property.
type AccessTypeRm struct {
}
