/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type JobTypeAnyOf string

// List of JobTypeAnyOf
const (
	IMMEDIATE_MDT_ONLY JobTypeAnyOf = "IMMEDIATE_MDT_ONLY"
	LOGGED_MDT_ONLY JobTypeAnyOf = "LOGGED_MDT_ONLY"
	TRACE_ONLY JobTypeAnyOf = "TRACE_ONLY"
	IMMEDIATE_MDT_AND_TRACE JobTypeAnyOf = "IMMEDIATE_MDT_AND_TRACE"
	RLF_REPORTS_ONLY JobTypeAnyOf = "RLF_REPORTS_ONLY"
	RCEF_REPORTS_ONLY JobTypeAnyOf = "RCEF_REPORTS_ONLY"
	LOGGED_MBSFN_MDT JobTypeAnyOf = "LOGGED_MBSFN_MDT"
)
