/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type GpsiTypeAnyOf string

// List of GpsiTypeAnyOf
const (
	MSISDN       GpsiTypeAnyOf = "MSISDN"
	EXT_ID       GpsiTypeAnyOf = "EXT_ID"
	EXT_GROUP_ID GpsiTypeAnyOf = "EXT_GROUP_ID"
)
