/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AmfUpdatedEventSubscription - Represents a successful update on an AMF Event Subscription
type AmfUpdatedEventSubscription struct {
	Subscription AmfEventSubscription `json:"subscription"`

	ReportList []AmfEventReport `json:"reportList,omitempty"`
}
