/*
 * Npcf_AMPolicyAuthorization Service API
 *
 * PCF Access and Mobility Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AmEventNotification - Describes the notification of a subscription.
type AmEventNotification struct {
	Event AmEvent `json:"event"`

	AppliedCov ServiceAreaCoverageInfo `json:"appliedCov,omitempty"`

	PduidInfo PduidInformation `json:"pduidInfo,omitempty"`
}
