/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.0-alpha.4
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AllowedSnssai - Contains the authorized S-NSSAI and optional mapped home S-NSSAI and network slice instance information 
type AllowedSnssai struct {

	AllowedSnssai Snssai `json:"allowedSnssai"`

	NsiInformationList []NsiInformation `json:"nsiInformationList,omitempty"`

	MappedHomeSnssai Snssai `json:"mappedHomeSnssai,omitempty"`
}
