/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type ImsVoPsAnyOf string

// List of ImsVoPsAnyOf
const (
	HOMOGENEOUS_SUPPORT        ImsVoPsAnyOf = "HOMOGENEOUS_SUPPORT"
	HOMOGENEOUS_NON_SUPPORT    ImsVoPsAnyOf = "HOMOGENEOUS_NON_SUPPORT"
	NON_HOMOGENEOUS_OR_UNKNOWN ImsVoPsAnyOf = "NON_HOMOGENEOUS_OR_UNKNOWN"
)
