/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// EthernetFlowInfo - Identifies an UL/DL ethernet flow.
type EthernetFlowInfo struct {
	EthFlows []EthFlowDescription `json:"ethFlows,omitempty"`

	FlowNumber int32 `json:"flowNumber"`
}
