/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// IpEndPoint - IP addressing information of a given NFService; it consists on, e.g. IP address, TCP port, transport protocol...
type IpEndPoint struct {

	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	Ipv4Address string `json:"ipv4Address,omitempty"`

	Ipv6Address Ipv6Addr `json:"ipv6Address,omitempty"`

	Transport TransportProtocol1 `json:"transport,omitempty"`

	Port int32 `json:"port,omitempty"`
}
