/*
 * Namf_MT
 *
 * AMF Mobile Terminated Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.2.0-alpha.3
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AdditionInfoEnableUeReachability - Additional information to be returned in EnableUeReachability error response
type AdditionInfoEnableUeReachability struct {

	// indicating a time in seconds.
	MaxWaitingTime int32 `json:"maxWaitingTime,omitempty"`
}
