/*
 * Namf_MBSBroadcast
 *
 * AMF MBSBroadcast Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type OperationStatusAnyOf string

// List of OperationStatusAnyOf
const (
	START_COMPLETE OperationStatusAnyOf = "MBS_SESSION_START_COMPLETE"
	START_INCOMPLETE OperationStatusAnyOf = "MBS_SESSION_START_INCOMPLETE"
	UPDATE_COMPLETE OperationStatusAnyOf = "MBS_SESSION_UPDATE_COMPLETE"
	UPDATE_INCOMPLETE OperationStatusAnyOf = "MBS_SESSION_UPDATE_INCOMPLETE"
)
