/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// QosFlowReleaseRequestItem - Individual QoS flow requested to be released
type QosFlowReleaseRequestItem struct {

	// Unsigned integer identifying a QoS flow, within the range 0 to 63.
	Qfi int32 `json:"qfi"`

	// string with format 'bytes' as defined in OpenAPI
	QosRules string `json:"qosRules,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	QosFlowDescription string `json:"qosFlowDescription,omitempty"`
}
