/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type ConditionEventTypeAnyOf string

// List of ConditionEventTypeAnyOf
const (
	ADDED   ConditionEventTypeAnyOf = "NF_ADDED"
	REMOVED ConditionEventTypeAnyOf = "NF_REMOVED"
)
