/*
 * Namf_MBSBroadcast
 *
 * AMF MBSBroadcast Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ContextUpdateReqData - Data within ContextUpdate Request
type ContextUpdateReqData struct {

	MbsServiceArea MbsServiceArea `json:"mbsServiceArea,omitempty"`

	N2MbsSmInfo N2MbsSmInfo `json:"n2MbsSmInfo,omitempty"`

	// String providing an URI formatted according to RFC 3986
	NotifyUri string `json:"notifyUri,omitempty"`

	// indicating a time in seconds.
	MaxResponseTime int32 `json:"maxResponseTime,omitempty"`
}
