/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type DeregistrationReasonAnyOf string

// List of DeregistrationReasonAnyOf
const (
	UE_INITIAL_REGISTRATION DeregistrationReasonAnyOf = "UE_INITIAL_REGISTRATION"
	UE_REGISTRATION_AREA_CHANGE DeregistrationReasonAnyOf = "UE_REGISTRATION_AREA_CHANGE"
	SUBSCRIPTION_WITHDRAWN DeregistrationReasonAnyOf = "SUBSCRIPTION_WITHDRAWN"
	_5_GS_TO_EPS_MOBILITY DeregistrationReasonAnyOf = "5GS_TO_EPS_MOBILITY"
	_5_GS_TO_EPS_MOBILITY_UE_INITIAL_REGISTRATION DeregistrationReasonAnyOf = "5GS_TO_EPS_MOBILITY_UE_INITIAL_REGISTRATION"
	REREGISTRATION_REQUIRED DeregistrationReasonAnyOf = "REREGISTRATION_REQUIRED"
	SMF_CONTEXT_TRANSFERRED DeregistrationReasonAnyOf = "SMF_CONTEXT_TRANSFERRED"
)
