/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// DownlinkDataNotificationControl - Contains the downlink data notification control information.
type DownlinkDataNotificationControl struct {
	NotifCtrlInds []NotificationControlIndication `json:"notifCtrlInds,omitempty"`

	TypesOfNotif []DlDataDeliveryStatus `json:"typesOfNotif,omitempty"`
}
