/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// LinksValueSchema - A list of mutually exclusive alternatives of 1 or more links
type LinksValueSchema struct {

	// String providing an URI formatted according to RFC 3986
	Href string `json:"href,omitempty"`
}
