/*
 * Npcf_AMPolicyAuthorization Service API
 *
 * PCF Access and Mobility Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AmEventsSubscData - It represents the AM Policy Events Subscription subresource and identifies the events the application subscribes to.
type AmEventsSubscData struct {

	// String providing an URI formatted according to RFC 3986
	EventNotifUri string `json:"eventNotifUri"`

	Events []AmEventData `json:"events,omitempty"`
}
