/*
 * Npcf_UEPolicyControl
 *
 * UE Policy Control Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// RequestTrigger - Possible values are: - LOC_CH: Location change (tracking area). The tracking area of the UE has changed. - PRA_CH: Change of UE presence in PRA. The AMF reports the current presence status of the UE   in a Presence Reporting Area, and notifies that the UE enters/leaves the Presence Reporting   Area. - UE_POLICY: A MANAGE UE POLICY COMPLETE message or a MANAGE UE POLICY COMMAND REJECT   message, as defined in Annex D.5 of 3GPP TS 24.501 or a \"UE POLICY PROVISIONING REQUEST\"   message, as defined in clause 7.2.1.1 of 3GPP TS 24.587 , has been received by the AMF   and is being forwarded. - PLMN_CH: PLMN change. the serving PLMN of UE has changed.  - CON_STATE_CH: Connectivity state change: the connectivity state of UE has changed.  - GROUP_ID_LIST_CHG: UE Internal Group Identifier(s) has changed. This policy control request   trigger does not require a subscription - UE_CAP_CH: UE Capabilities change: the UE provided 5G ProSe capabilities have changed.   This policy control request trigger does not require subscription.  
type RequestTrigger struct {
}
