/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AccNetChId - Contains the access network charging identifier for the PCC rule(s) or for the whole PDU session.
type AccNetChId struct {

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer.
	AccNetChaIdValue int32 `json:"accNetChaIdValue,omitempty"`

	// A character string containing the access network charging id.
	AccNetChargId string `json:"accNetChargId,omitempty"`

	// Contains the identifier of the PCC rule(s) associated to the provided Access Network Charging Identifier.
	RefPccRuleIds []string `json:"refPccRuleIds,omitempty"`

	// When it is included and set to true, indicates the Access Network Charging Identifier applies to the whole PDU Session
	SessionChScope bool `json:"sessionChScope,omitempty"`
}
