/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type RequestedRuleDataTypeAnyOf string

// List of RequestedRuleDataTypeAnyOf
const (
	CH_ID         RequestedRuleDataTypeAnyOf = "CH_ID"
	MS_TIME_ZONE  RequestedRuleDataTypeAnyOf = "MS_TIME_ZONE"
	USER_LOC_INFO RequestedRuleDataTypeAnyOf = "USER_LOC_INFO"
)
