/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type FailureOneOf string

// List of FailureOneOf
const (
	UE_NOT_REACHABLE FailureOneOf = "UE_NOT_REACHABLE"
	UNKNOWN          FailureOneOf = "UNKNOWN"
)
