/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.0-alpha.4
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// SubscribedSnssai - Contains the subscribed S-NSSAI
type SubscribedSnssai struct {
	SubscribedSnssai Snssai `json:"subscribedSnssai"`

	DefaultIndication bool `json:"defaultIndication,omitempty"`

	SubscribedNsSrgList []string `json:"subscribedNsSrgList,omitempty"`
}
