/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// VendorSpecificFeature - Information about a vendor-specific feature
type VendorSpecificFeature struct {
	FeatureName string `json:"featureName"`

	FeatureVersion string `json:"featureVersion"`
}
