/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"time"
)

// AmfEventReport - Represents a report triggered by a subscribed event type
type AmfEventReport struct {

	Type AmfEventType `json:"type"`

	State AmfEventState `json:"state"`

	// string with format 'date-time' as defined in OpenAPI.
	TimeStamp time.Time `json:"timeStamp"`

	// String providing an URI formatted according to RFC 3986
	SubscriptionId string `json:"subscriptionId,omitempty"`

	AnyUe bool `json:"anyUe,omitempty"`

	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause 2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2 of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2 of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of 3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall only contain characters allowed according to the \"lower-with-hyphen\" naming convention defined in 3GPP TS 29.501. 
	Supi string `json:"supi,omitempty"`

	AreaList []AmfEventArea `json:"areaList,omitempty"`

	RefId int32 `json:"refId,omitempty"`

	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-<extid>, where <extid>  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
	Gpsi string `json:"gpsi,omitempty"`

	// String representing a Permanent Equipment Identifier that may contain - an IMEI or IMEISV, as  specified in clause 6.2 of 3GPP TS 23.003; a MAC address for a 5G-RG or FN-RG via wireline  access, with an indication that this address cannot be trusted for regulatory purpose if this  address cannot be used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7  of 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345.  
	Pei string `json:"pei,omitempty"`

	Location UserLocation `json:"location,omitempty"`

	AdditionalLocation UserLocation `json:"additionalLocation,omitempty"`

	// String with format \"<time-numoffset>\" optionally appended by \"<daylightSavingTime>\", where  -  <time-numoffset> shall represent the time zone adjusted for daylight saving time and be encoded as time-numoffset as defined in clause 5.6 of IETF RFC 3339;  - <daylightSavingTime> shall represent the adjustment that has been made and shall be encoded as \"+1\" or \"+2\" for a +1 or +2 hours adjustment.  The example is for 8 hours behind UTC, +1 hour adjustment for Daylight Saving Time. 
	Timezone string `json:"timezone,omitempty"`

	AccessTypeList []AccessType `json:"accessTypeList,omitempty"`

	RmInfoList []RmInfo `json:"rmInfoList,omitempty"`

	CmInfoList []CmInfo `json:"cmInfoList,omitempty"`

	Reachability UeReachability `json:"reachability,omitempty"`

	CommFailure CommunicationFailure `json:"commFailure,omitempty"`

	LossOfConnectReason LossOfConnectivityReason `json:"lossOfConnectReason,omitempty"`

	NumberOfUes int32 `json:"numberOfUes,omitempty"`

	Var5gsUserStateList []Model5GsUserStateInfo `json:"5gsUserStateList,omitempty"`

	TypeCode string `json:"typeCode,omitempty"`

	RegistrationNumber int32 `json:"registrationNumber,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	MaxAvailabilityTime time.Time `json:"maxAvailabilityTime,omitempty"`

	UeIdExt []UeidExt `json:"ueIdExt,omitempty"`

	SnssaiTaiList []SnssaiTaiMapping `json:"snssaiTaiList,omitempty"`

	IdleStatusIndication IdleStatusIndication `json:"idleStatusIndication,omitempty"`

	UeAccessBehaviorTrends []UeAccessBehaviorReportItem `json:"ueAccessBehaviorTrends,omitempty"`

	UeLocationTrends []UeLocationTrendsReportItem `json:"ueLocationTrends,omitempty"`

	MmTransLocationReportList []MmTransactionLocationReportItem `json:"mmTransLocationReportList,omitempty"`

	MmTransSliceReportList []MmTransactionSliceReportItem `json:"mmTransSliceReportList,omitempty"`
}
