/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// IpFlowInfo - Identifies an UL/DL IP flow.
type IpFlowInfo struct {
	IpFlows []string `json:"ipFlows,omitempty"`

	FlowNumber int32 `json:"flowNumber"`
}
