/*
 * Naf_EventExposure
 *
 * AF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// CollectiveBehaviourInfo - Contains the collective behaviour information to be reported to the subscriber.
type CollectiveBehaviourInfo struct {
	ColAttrib []PerUeAttribute `json:"colAttrib"`

	// Total number of UEs that fulfil a collective within the area of interest.
	NoOfUes int32 `json:"noOfUes,omitempty"`

	AppIds []string `json:"appIds,omitempty"`

	ExtUeIds []string `json:"extUeIds,omitempty"`

	UeIds []string `json:"ueIds,omitempty"`
}
