/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type LoggingIntervalMdtAnyOf string

// List of LoggingIntervalMdtAnyOf
const (
	_128 LoggingIntervalMdtAnyOf = "128"
	_256 LoggingIntervalMdtAnyOf = "256"
	_512 LoggingIntervalMdtAnyOf = "512"
	_3072 LoggingIntervalMdtAnyOf = "3072"
	_4096 LoggingIntervalMdtAnyOf = "4096"
	_6144 LoggingIntervalMdtAnyOf = "6144"
)
