/*
 * Npcf_UEPolicyControl
 *
 * UE Policy Control Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type ProSeCapabilityAnyOf string

// List of ProSeCapabilityAnyOf
const (
	DD ProSeCapabilityAnyOf = "PROSE_DD"
	DC ProSeCapabilityAnyOf = "PROSE_DC"
	L2_U2_N_RELAY ProSeCapabilityAnyOf = "PROSE_L2_U2N_RELAY"
	L3_U2_N_RELAY ProSeCapabilityAnyOf = "PROSE_L3_U2N_RELAY"
	L2_REMOTE_UE ProSeCapabilityAnyOf = "PROSE_L2_REMOTE_UE"
	L3_REMOTE_UE ProSeCapabilityAnyOf = "PROSE_L3_REMOTE_UE"
)
