/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// UnTrustAfInfo - Information of a untrusted AF Instance
type UnTrustAfInfo struct {

	AfId string `json:"afId"`

	SNssaiInfoList []SnssaiInfoItem `json:"sNssaiInfoList,omitempty"`

	MappingInd bool `json:"mappingInd,omitempty"`
}
