/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ContextDataSets - Contains the context data sets.
type ContextDataSets struct {

	Amf3Gpp Amf3GppAccessRegistration `json:"amf3Gpp,omitempty"`

	AmfNon3Gpp AmfNon3GppAccessRegistration `json:"amfNon3Gpp,omitempty"`

	SdmSubscriptions []SdmSubscription `json:"sdmSubscriptions,omitempty"`

	EeSubscriptions []EeSubscription `json:"eeSubscriptions,omitempty"`

	Smsf3GppAccess SmsfRegistration `json:"smsf3GppAccess,omitempty"`

	SmsfNon3GppAccess SmsfRegistration `json:"smsfNon3GppAccess,omitempty"`

	SubscriptionDataSubscriptions []SubscriptionDataSubscriptions `json:"subscriptionDataSubscriptions,omitempty"`

	// The list of all the SMF registrations of a UE.
	SmfRegistrations []SmfRegistration `json:"smfRegistrations,omitempty"`

	IpSmGw IpSmGwRegistration `json:"ipSmGw,omitempty"`
}
