/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type SharedData struct {
	SharedDataId string `json:"sharedDataId"`

	SharedAmData AccessAndMobilitySubscriptionData1 `json:"sharedAmData,omitempty"`

	SharedSmsSubsData SmsSubscriptionData1 `json:"sharedSmsSubsData,omitempty"`

	SharedSmsMngSubsData SmsManagementSubscriptionData1 `json:"sharedSmsMngSubsData,omitempty"`

	// A map(list of key-value pairs) where Dnn, or optionally the Wildcard DNN, serves as key of DnnConfiguration
	SharedDnnConfigurations map[string]DnnConfiguration1 `json:"sharedDnnConfigurations,omitempty"`

	SharedTraceData *TraceData `json:"sharedTraceData,omitempty"`

	// A map(list of key-value pairs) where singleNssai serves as key of SnssaiInfo
	SharedSnssaiInfos map[string]SnssaiInfo `json:"sharedSnssaiInfos,omitempty"`

	// A map(list of key-value pairs) where GroupId serves as key of VnGroupData
	SharedVnGroupDatas map[string]VnGroupData `json:"sharedVnGroupDatas,omitempty"`

	// A map(list of key-value pairs) where JSON pointer pointing to an attribute within the SharedData serves as key of SharedDataTreatmentInstruction
	TreatmentInstructions map[string]SharedDataTreatmentInstruction `json:"treatmentInstructions,omitempty"`

	SharedSmSubsData SessionManagementSubscriptionData1 `json:"sharedSmSubsData,omitempty"`

	SharedEcsAddrConfigInfo *EcsAddrConfigInfo1 `json:"sharedEcsAddrConfigInfo,omitempty"`
}
