/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type SorUpdateIndicatorAnyOf string

// List of SorUpdateIndicatorAnyOf
const (
	INITIAL_REGISTRATION SorUpdateIndicatorAnyOf = "INITIAL_REGISTRATION"
	EMERGENCY_REGISTRATION SorUpdateIndicatorAnyOf = "EMERGENCY_REGISTRATION"
)
