/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AccuUsageReport - Contains the accumulated usage report information.
type AccuUsageReport struct {

	// An id referencing UsageMonitoringData objects associated with this usage report.
	RefUmIds string `json:"refUmIds"`

	// Unsigned integer identifying a volume in units of bytes.
	VolUsage int64 `json:"volUsage,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	VolUsageUplink int64 `json:"volUsageUplink,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	VolUsageDownlink int64 `json:"volUsageDownlink,omitempty"`

	// indicating a time in seconds.
	TimeUsage int32 `json:"timeUsage,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	NextVolUsage int64 `json:"nextVolUsage,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	NextVolUsageUplink int64 `json:"nextVolUsageUplink,omitempty"`

	// Unsigned integer identifying a volume in units of bytes.
	NextVolUsageDownlink int64 `json:"nextVolUsageDownlink,omitempty"`

	// indicating a time in seconds.
	NextTimeUsage int32 `json:"nextTimeUsage,omitempty"`
}
