/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type PduSessionRelCauseAnyOf string

// List of PduSessionRelCauseAnyOf
const (
	PS_TO_CS_HO PduSessionRelCauseAnyOf = "PS_TO_CS_HO"
	RULE_ERROR PduSessionRelCauseAnyOf = "RULE_ERROR"
)
