/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"time"
)

// PduSessionCreateData - Data within Create Request
type PduSessionCreateData struct {

	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause 2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2 of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2 of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of 3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall only contain characters allowed according to the \"lower-with-hyphen\" naming convention defined in 3GPP TS 29.501. 
	Supi string `json:"supi,omitempty"`

	UnauthenticatedSupi bool `json:"unauthenticatedSupi,omitempty"`

	// String representing a Permanent Equipment Identifier that may contain - an IMEI or IMEISV, as  specified in clause 6.2 of 3GPP TS 23.003; a MAC address for a 5G-RG or FN-RG via wireline  access, with an indication that this address cannot be trusted for regulatory purpose if this  address cannot be used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7  of 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345.  
	Pei string `json:"pei,omitempty"`

	// Unsigned integer identifying a PDU session, within the range 0 to 255, as specified in  clause 11.2.3.1b, bits 1 to 8, of 3GPP TS 24.007. If the PDU Session ID is allocated by the  Core Network for UEs not supporting N1 mode, reserved range 64 to 95 is used. PDU Session ID  within the reserved range is only visible in the Core Network.  
	PduSessionId int32 `json:"pduSessionId,omitempty"`

	// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003; it shall contain either a DNN Network Identifier, or a full DNN with both the Network Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots (e.g. \"Label1.Label2.Label3\").
	Dnn string `json:"dnn"`

	// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003; it shall contain either a DNN Network Identifier, or a full DNN with both the Network Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots (e.g. \"Label1.Label2.Label3\").
	SelectedDnn string `json:"selectedDnn,omitempty"`

	SNssai Snssai `json:"sNssai,omitempty"`

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	VsmfId string `json:"vsmfId,omitempty"`

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	IsmfId string `json:"ismfId,omitempty"`

	ServingNetwork PlmnIdNid `json:"servingNetwork"`

	RequestType RequestType `json:"requestType,omitempty"`

	EpsBearerId []int32 `json:"epsBearerId,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	PgwS8cFteid string `json:"pgwS8cFteid,omitempty"`

	// String providing an URI formatted according to RFC 3986
	VsmfPduSessionUri string `json:"vsmfPduSessionUri,omitempty"`

	// String providing an URI formatted according to RFC 3986
	IsmfPduSessionUri string `json:"ismfPduSessionUri,omitempty"`

	VcnTunnelInfo TunnelInfo `json:"vcnTunnelInfo,omitempty"`

	IcnTunnelInfo TunnelInfo `json:"icnTunnelInfo,omitempty"`

	N9ForwardingTunnelInfo TunnelInfo `json:"n9ForwardingTunnelInfo,omitempty"`

	AdditionalCnTunnelInfo TunnelInfo `json:"additionalCnTunnelInfo,omitempty"`

	AnType AccessType `json:"anType"`

	AdditionalAnType AccessType `json:"additionalAnType,omitempty"`

	RatType RatType `json:"ratType,omitempty"`

	UeLocation UserLocation `json:"ueLocation,omitempty"`

	// String with format \"<time-numoffset>\" optionally appended by \"<daylightSavingTime>\", where  -  <time-numoffset> shall represent the time zone adjusted for daylight saving time and be encoded as time-numoffset as defined in clause 5.6 of IETF RFC 3339;  - <daylightSavingTime> shall represent the adjustment that has been made and shall be encoded as \"+1\" or \"+2\" for a +1 or +2 hours adjustment.  The example is for 8 hours behind UTC, +1 hour adjustment for Daylight Saving Time. 
	UeTimeZone string `json:"ueTimeZone,omitempty"`

	AddUeLocation UserLocation `json:"addUeLocation,omitempty"`

	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-<extid>, where <extid>  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
	Gpsi string `json:"gpsi,omitempty"`

	N1SmInfoFromUe RefToBinaryData `json:"n1SmInfoFromUe,omitempty"`

	UnknownN1SmInfo RefToBinaryData `json:"unknownN1SmInfo,omitempty"`

	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
	SupportedFeatures string `json:"supportedFeatures,omitempty"`

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	HPcfId string `json:"hPcfId,omitempty"`

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	PcfId string `json:"pcfId,omitempty"`

	// Identifier of a group of NFs.
	PcfGroupId string `json:"pcfGroupId,omitempty"`

	// NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted as the following string \"  set<Set ID>.<nftype>set.5gc.mnc<MNC>.mcc<MCC>\", or \"set<SetID>.  <NFType>set.5gc.nid<NID>.mnc<MNC>.mcc<MCC>\" with <MCC> encoded as defined in clause 5.4.2  (\"Mcc\" data type definition) <MNC> encoded as defined in clause 5.4.2 (\"Mnc\" data type  definition) <NFType> encoded as a value defined in Table 6.1.6.3.3-1 of 3GPP TS 29.510 but  with lower case characters <Set ID> encoded as a string of characters consisting of alphabetic  characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that shall end with either an  alphabetic character or a digit.  
	PcfSetId string `json:"pcfSetId,omitempty"`

	HoPreparationIndication bool `json:"hoPreparationIndication,omitempty"`

	SelMode DnnSelectionMode `json:"selMode,omitempty"`

	AlwaysOnRequested bool `json:"alwaysOnRequested,omitempty"`

	// Identifier of a group of NFs.
	UdmGroupId string `json:"udmGroupId,omitempty"`

	RoutingIndicator string `json:"routingIndicator,omitempty"`

	HNwPubKeyId int32 `json:"hNwPubKeyId,omitempty"`

	EpsInterworkingInd EpsInterworkingIndication `json:"epsInterworkingInd,omitempty"`

	VSmfServiceInstanceId string `json:"vSmfServiceInstanceId,omitempty"`

	ISmfServiceInstanceId string `json:"iSmfServiceInstanceId,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	RecoveryTime time.Time `json:"recoveryTime,omitempty"`

	RoamingChargingProfile RoamingChargingProfile `json:"roamingChargingProfile,omitempty"`

	ChargingId string `json:"chargingId,omitempty"`

	// Unsigned integer identifying a PDU session, within the range 0 to 255, as specified in  clause 11.2.3.1b, bits 1 to 8, of 3GPP TS 24.007. If the PDU Session ID is allocated by the  Core Network for UEs not supporting N1 mode, reserved range 64 to 95 is used. PDU Session ID  within the reserved range is only visible in the Core Network.  
	OldPduSessionId int32 `json:"oldPduSessionId,omitempty"`

	// EPS bearer context status
	EpsBearerCtxStatus string `json:"epsBearerCtxStatus,omitempty"`

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	AmfNfId string `json:"amfNfId,omitempty"`

	Guami Guami `json:"guami,omitempty"`

	MaxIntegrityProtectedDataRateUl MaxIntegrityProtectedDataRate `json:"maxIntegrityProtectedDataRateUl,omitempty"`

	MaxIntegrityProtectedDataRateDl MaxIntegrityProtectedDataRate `json:"maxIntegrityProtectedDataRateDl,omitempty"`

	CpCiotEnabled bool `json:"cpCiotEnabled,omitempty"`

	CpOnlyInd bool `json:"cpOnlyInd,omitempty"`

	InvokeNef bool `json:"invokeNef,omitempty"`

	MaRequestInd bool `json:"maRequestInd,omitempty"`

	MaNwUpgradeInd bool `json:"maNwUpgradeInd,omitempty"`

	DnaiList []string `json:"dnaiList,omitempty"`

	PresenceInLadn PresenceState `json:"presenceInLadn,omitempty"`

	SecondaryRatUsageInfo []SecondaryRatUsageInfo `json:"secondaryRatUsageInfo,omitempty"`

	SmallDataRateStatus SmallDataRateStatus `json:"smallDataRateStatus,omitempty"`

	ApnRateStatus ApnRateStatus `json:"apnRateStatus,omitempty"`

	DlServingPlmnRateCtl int32 `json:"dlServingPlmnRateCtl,omitempty"`

	UpSecurityInfo UpSecurityInfo `json:"upSecurityInfo,omitempty"`

	VplmnQos VplmnQos `json:"vplmnQos,omitempty"`

	// String providing an URI formatted according to RFC 3986
	OldSmContextRef string `json:"oldSmContextRef,omitempty"`

	RedundantPduSessionInfo RedundantPduSessionInformation `json:"redundantPduSessionInfo,omitempty"`

	// String providing an URI formatted according to RFC 3986
	OldPduSessionRef string `json:"oldPduSessionRef,omitempty"`

	SmPolicyNotifyInd bool `json:"smPolicyNotifyInd,omitempty"`

	PcfUeCallbackInfo *PcfUeCallbackInfo `json:"pcfUeCallbackInfo,omitempty"`

	SatelliteBackhaulCat SatelliteBackhaulCategory `json:"satelliteBackhaulCat,omitempty"`

	UpipSupported bool `json:"upipSupported,omitempty"`
}
