/*
 * LMF Location
 *
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.4
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type PositioningMethodAnyOf string

// List of PositioningMethodAnyOf
const (
	CELLID PositioningMethodAnyOf = "CELLID"
	ECID PositioningMethodAnyOf = "ECID"
	OTDOA PositioningMethodAnyOf = "OTDOA"
	BAROMETRIC_PRESSURE PositioningMethodAnyOf = "BAROMETRIC_PRESSURE"
	BLUETOOTH PositioningMethodAnyOf = "BLUETOOTH"
	MOTION_SENSOR PositioningMethodAnyOf = "MOTION_SENSOR"
	DL_TDOA PositioningMethodAnyOf = "DL_TDOA"
	DL_AOD PositioningMethodAnyOf = "DL_AOD"
	MULTI_RTT PositioningMethodAnyOf = "MULTI-RTT"
	NR_ECID PositioningMethodAnyOf = "NR_ECID"
	UL_TDOA PositioningMethodAnyOf = "UL_TDOA"
	UL_AOA PositioningMethodAnyOf = "UL_AOA"
	NETWORK_SPECIFIC PositioningMethodAnyOf = "NETWORK_SPECIFIC"
)
