/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type RequestIndicationAnyOf string

// List of RequestIndicationAnyOf
const (
	UE_REQ_PDU_SES_MOD RequestIndicationAnyOf = "UE_REQ_PDU_SES_MOD"
	UE_REQ_PDU_SES_REL RequestIndicationAnyOf = "UE_REQ_PDU_SES_REL"
	PDU_SES_MOB RequestIndicationAnyOf = "PDU_SES_MOB"
	NW_REQ_PDU_SES_AUTH RequestIndicationAnyOf = "NW_REQ_PDU_SES_AUTH"
	NW_REQ_PDU_SES_MOD RequestIndicationAnyOf = "NW_REQ_PDU_SES_MOD"
	NW_REQ_PDU_SES_REL RequestIndicationAnyOf = "NW_REQ_PDU_SES_REL"
	EBI_ASSIGNMENT_REQ RequestIndicationAnyOf = "EBI_ASSIGNMENT_REQ"
	REL_DUE_TO_5_G_AN_REQUEST RequestIndicationAnyOf = "REL_DUE_TO_5G_AN_REQUEST"
)
