/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// EcsServerAddr - Contains the Edge Configuration Server Address Configuration Information as defined in clause 5.2.3.6.1 of 3GPP TS 23.502.
type EcsServerAddr struct {
	EcsFqdnList []string `json:"ecsFqdnList,omitempty"`

	EcsIpAddressList []IpAddr `json:"ecsIpAddressList,omitempty"`

	EcsProviderId string `json:"ecsProviderId,omitempty"`
}
