/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AmfUpdateEventSubscriptionItem - Document describing the modification(s) to an AMF Event Subscription
type AmfUpdateEventSubscriptionItem struct {

	Op string `json:"op"`

	Path string `json:"path"`

	Value AmfEvent `json:"value,omitempty"`

	PresenceInfo PresenceInfo `json:"presenceInfo,omitempty"`

	ExcludeSupiList []string `json:"excludeSupiList,omitempty"`

	ExcludeGpsiList []string `json:"excludeGpsiList,omitempty"`

	IncludeSupiList []string `json:"includeSupiList,omitempty"`

	IncludeGpsiList []string `json:"includeGpsiList,omitempty"`
}
