/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// SgsnAddress - describes the address of the SGSN
type SgsnAddress struct {

	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	SgsnIpv4Addr string `json:"sgsnIpv4Addr,omitempty"`

	SgsnIpv6Addr Ipv6Addr `json:"sgsnIpv6Addr,omitempty"`
}
