/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// SmPolicyControl - Contains the parameters used to request the SM policies and the SM policies authorized by the PCF.
type SmPolicyControl struct {

	Context SmPolicyContextData `json:"context"`

	Policy SmPolicyDecision `json:"policy"`
}
