/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type ServiceInfoStatusAnyOf string

// List of ServiceInfoStatusAnyOf
const (
	FINAL ServiceInfoStatusAnyOf = "FINAL"
	PRELIMINARY ServiceInfoStatusAnyOf = "PRELIMINARY"
)
