/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// IndirectDataForwardingTunnelInfo - Indirect Data Forwarding Tunnel Information
type IndirectDataForwardingTunnelInfo struct {

	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	Ipv4Addr string `json:"ipv4Addr,omitempty"`

	Ipv6Addr Ipv6Addr `json:"ipv6Addr,omitempty"`

	// GTP Tunnel Endpoint Identifier
	GtpTeid string `json:"gtpTeid"`

	// Data Radio Bearer Identity
	DrbId int32 `json:"drbId,omitempty"`

	// indicates first, second or third additional indirect data forwarding tunnel
	AdditionalTnlNb int32 `json:"additionalTnlNb,omitempty"`
}
