/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type FailureCodeAnyOf string

// List of FailureCodeAnyOf
const (
	UNK_RULE_ID FailureCodeAnyOf = "UNK_RULE_ID"
	RA_GR_ERR FailureCodeAnyOf = "RA_GR_ERR"
	SER_ID_ERR FailureCodeAnyOf = "SER_ID_ERR"
	NF_MAL FailureCodeAnyOf = "NF_MAL"
	RES_LIM FailureCodeAnyOf = "RES_LIM"
	MAX_NR_QO_S_FLOW FailureCodeAnyOf = "MAX_NR_QoS_FLOW"
	MISS_FLOW_INFO FailureCodeAnyOf = "MISS_FLOW_INFO"
	RES_ALLO_FAIL FailureCodeAnyOf = "RES_ALLO_FAIL"
	UNSUCC_QOS_VAL FailureCodeAnyOf = "UNSUCC_QOS_VAL"
	INCOR_FLOW_INFO FailureCodeAnyOf = "INCOR_FLOW_INFO"
	PS_TO_CS_HAN FailureCodeAnyOf = "PS_TO_CS_HAN"
	APP_ID_ERR FailureCodeAnyOf = "APP_ID_ERR"
	NO_QOS_FLOW_BOUND FailureCodeAnyOf = "NO_QOS_FLOW_BOUND"
	FILTER_RES FailureCodeAnyOf = "FILTER_RES"
	MISS_REDI_SER_ADDR FailureCodeAnyOf = "MISS_REDI_SER_ADDR"
	CM_END_USER_SER_DENIED FailureCodeAnyOf = "CM_END_USER_SER_DENIED"
	CM_CREDIT_CON_NOT_APP FailureCodeAnyOf = "CM_CREDIT_CON_NOT_APP"
	CM_AUTH_REJ FailureCodeAnyOf = "CM_AUTH_REJ"
	CM_USER_UNK FailureCodeAnyOf = "CM_USER_UNK"
	CM_RAT_FAILED FailureCodeAnyOf = "CM_RAT_FAILED"
	UE_STA_SUSP FailureCodeAnyOf = "UE_STA_SUSP"
	UNKNOWN_REF_ID FailureCodeAnyOf = "UNKNOWN_REF_ID"
	INCORRECT_COND_DATA FailureCodeAnyOf = "INCORRECT_COND_DATA"
	REF_ID_COLLISION FailureCodeAnyOf = "REF_ID_COLLISION"
	TRAFFIC_STEERING_ERROR FailureCodeAnyOf = "TRAFFIC_STEERING_ERROR"
	DNAI_STEERING_ERROR FailureCodeAnyOf = "DNAI_STEERING_ERROR"
	AN_GW_FAILE FailureCodeAnyOf = "AN_GW_FAILE"
	MAX_NR_PACKET_FILTERS_EXCEEDED FailureCodeAnyOf = "MAX_NR_PACKET_FILTERS_EXCEEDED"
)
