/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ProvisionedDataSets - Contains the provisioned data sets.
type ProvisionedDataSets struct {
	AmData AccessAndMobilitySubscriptionData `json:"amData,omitempty"`

	SmfSelData SmfSelectionSubscriptionData `json:"smfSelData,omitempty"`

	SmsSubsData SmsSubscriptionData `json:"smsSubsData,omitempty"`

	SmData SmSubsData `json:"smData,omitempty"`

	TraceData *TraceData `json:"traceData,omitempty"`

	SmsMngData SmsManagementSubscriptionData `json:"smsMngData,omitempty"`

	LcsPrivacyData LcsPrivacyData `json:"lcsPrivacyData,omitempty"`

	LcsMoData LcsMoData `json:"lcsMoData,omitempty"`

	LcsBcaData LcsBroadcastAssistanceTypesData `json:"lcsBcaData,omitempty"`

	V2xData V2xSubscriptionData `json:"v2xData,omitempty"`

	ProseData ProseSubscriptionData `json:"proseData,omitempty"`

	OdbData OdbData `json:"odbData,omitempty"`

	EeProfileData EeProfileData `json:"eeProfileData,omitempty"`

	PpProfileData PpProfileData `json:"ppProfileData,omitempty"`

	NiddAuthData AuthorizationData `json:"niddAuthData,omitempty"`

	MbsSubscriptionData MbsSubscriptionData1 `json:"mbsSubscriptionData,omitempty"`
}
