/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type FlowStatusAnyOf string

// List of FlowStatusAnyOf
const (
	ENABLED_UPLINK FlowStatusAnyOf = "ENABLED-UPLINK"
	ENABLED_DOWNLINK FlowStatusAnyOf = "ENABLED-DOWNLINK"
	ENABLED FlowStatusAnyOf = "ENABLED"
	DISABLED FlowStatusAnyOf = "DISABLED"
)
