/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// UnavailableAccessIndication - Indicates the access type of a MA PDU session that is unavailable. Possible values are   - 3GA_UNAVAILABLE   - N3GA_UNAVAILABLE 
type UnavailableAccessIndication struct {
}
