/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// TrafficDescriptorComponents - Traffic descriptor components for the requested URSP.
type TrafficDescriptorComponents struct {

	// Describes the operation systems and the corresponding applications for each operation systems. The key of map is osId.
	AppDescs map[string]AppDescriptor1 `json:"appDescs,omitempty"`

	// Represents a 3-tuple with protocol, server ip and server port for UL/DL application traffic. The content of the string has the same encoding as the IPFilterRule AVP value as defined in IETF RFC 6733.
	FlowDescs []string `json:"flowDescs,omitempty"`

	// FQDN(s) or a regular expression which are used as a domain name matching criteria.
	DomainDescs []string `json:"domainDescs,omitempty"`

	// Descriptor(s) for destination information of non-IP traffic in which only ethernet flow description is defined.
	EthFlowDescs []EthFlowDescription `json:"ethFlowDescs,omitempty"`

	// This is matched against the DNN information provided by the application.
	Dnns []string `json:"dnns,omitempty"`

	// This is matched against the information provided by a UE application when it requests a network connection with certain capabilities.
	ConnCaps []ConnectionCapabilities `json:"connCaps,omitempty"`
}
