/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// MediaComponentRm - This data type is defined in the same way as the MediaComponent data type, but with the OpenAPI nullable property set to true.
type MediaComponentRm struct {

	// Contains an AF application identifier.
	AfAppId string `json:"afAppId,omitempty"`

	AfRoutReq *AfRoutingRequirementRm `json:"afRoutReq,omitempty"`

	QosReference *string `json:"qosReference,omitempty"`

	AltSerReqs *[]string `json:"altSerReqs,omitempty"`

	// Contains removable alternative service requirements that include individual QoS parameter sets.
	AltSerReqsData *[]AlternativeServiceRequirementsData `json:"altSerReqsData,omitempty"`

	DisUeNotif bool `json:"disUeNotif,omitempty"`

	// Represents the content version of some content.
	ContVer int32 `json:"contVer,omitempty"`

	Codecs []string `json:"codecs,omitempty"`

	// string with format 'float' as defined in OpenAPI with the OpenAPI defined 'nullable: true' property.
	DesMaxLatency *float32 `json:"desMaxLatency,omitempty"`

	// string with format 'float' as defined in OpenAPI with the OpenAPI defined 'nullable: true' property.
	DesMaxLoss *float32 `json:"desMaxLoss,omitempty"`

	FlusId *string `json:"flusId,omitempty"`

	FStatus FlowStatus `json:"fStatus,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	MarBwDl *string `json:"marBwDl,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	MarBwUl *string `json:"marBwUl,omitempty"`

	// This data type is defined in the same way as the 'PacketLossRate' data type, but with the OpenAPI 'nullable: true' property.
	MaxPacketLossRateDl *int32 `json:"maxPacketLossRateDl,omitempty"`

	// This data type is defined in the same way as the 'PacketLossRate' data type, but with the OpenAPI 'nullable: true' property.
	MaxPacketLossRateUl *int32 `json:"maxPacketLossRateUl,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	MaxSuppBwDl *string `json:"maxSuppBwDl,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	MaxSuppBwUl *string `json:"maxSuppBwUl,omitempty"`

	MedCompN int32 `json:"medCompN"`

	// Contains the requested bitrate and filters for the set of service data flows identified by their common flow identifier. The key of the map is the fNum attribute.
	MedSubComps map[string]MediaSubComponentRm `json:"medSubComps,omitempty"`

	MedType MediaType `json:"medType,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	MinDesBwDl *string `json:"minDesBwDl,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	MinDesBwUl *string `json:"minDesBwUl,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	MirBwDl *string `json:"mirBwDl,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	MirBwUl *string `json:"mirBwUl,omitempty"`

	PreemptCap PreemptionCapabilityRm `json:"preemptCap,omitempty"`

	PreemptVuln PreemptionVulnerabilityRm `json:"preemptVuln,omitempty"`

	PrioSharingInd PrioritySharingIndicator `json:"prioSharingInd,omitempty"`

	ResPrio ReservPriority `json:"resPrio,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	RrBw *string `json:"rrBw,omitempty"`

	// This data type is defined in the same way as the 'BitRate' data type, but with the OpenAPI 'nullable: true' property.
	RsBw *string `json:"rsBw,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer with the OpenAPI 'nullable: true' property.
	SharingKeyDl *int32 `json:"sharingKeyDl,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer with the OpenAPI 'nullable: true' property.
	SharingKeyUl *int32 `json:"sharingKeyUl,omitempty"`

	TsnQos *TsnQosContainerRm `json:"tsnQos,omitempty"`

	TscaiInputDl *TscaiInputContainer `json:"tscaiInputDl,omitempty"`

	TscaiInputUl *TscaiInputContainer `json:"tscaiInputUl,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	TscaiTimeDom int32 `json:"tscaiTimeDom,omitempty"`
}
