/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type ReportAmountMdtAnyOf string

// List of ReportAmountMdtAnyOf
const (
	_1  ReportAmountMdtAnyOf = "1"
	_2  ReportAmountMdtAnyOf = "2"
	_4  ReportAmountMdtAnyOf = "4"
	_8  ReportAmountMdtAnyOf = "8"
	_16 ReportAmountMdtAnyOf = "16"
	_32 ReportAmountMdtAnyOf = "32"
	_64 ReportAmountMdtAnyOf = "64"
)
