/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// QosMonitoringData - Contains QoS monitoring related control information.
type QosMonitoringData struct {

	// Univocally identifies the QoS monitoring policy data within a PDU session.
	QmId string `json:"qmId"`

	// indicates the UL packet delay, DL packet delay and/or round trip packet delay between the UE and the UPF is to be monitored when the QoS Monitoring for URLLC is enabled for the service data flow.
	ReqQosMonParams []RequestedQosMonitoringParameter `json:"reqQosMonParams"`

	RepFreqs []ReportingFrequency `json:"repFreqs"`

	// Indicates the period of time in units of miliiseconds for DL packet delay.
	RepThreshDl *int32 `json:"repThreshDl,omitempty"`

	// Indicates the period of time in units of miliiseconds for UL packet delay.
	RepThreshUl *int32 `json:"repThreshUl,omitempty"`

	// Indicates the period of time in units of miliiseconds for round trip packet delay.
	RepThreshRp *int32 `json:"repThreshRp,omitempty"`

	// indicating a time in seconds with OpenAPI defined 'nullable: true' property.
	WaitTime *int32 `json:"waitTime,omitempty"`

	// indicating a time in seconds with OpenAPI defined 'nullable: true' property.
	RepPeriod *int32 `json:"repPeriod,omitempty"`

	// String providing an URI formatted according to RFC 3986 with the OpenAPI 'nullable: true' property.
	NotifyUri *string `json:"notifyUri,omitempty"`

	NotifyCorreId *string `json:"notifyCorreId,omitempty"`

	// Indicates that the direct event notification sent by UPF to the Local NEF or AF is requested if it is included and set to true.
	DirectNotifInd bool `json:"directNotifInd,omitempty"`
}
