/*
 * Nudm_MT
 *
 * UDM MT Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0-alpha.2
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// UeInfo - Represents UE information.
type UeInfo struct {

	TadsInfo UeContextInfo `json:"tadsInfo,omitempty"`

	UserState Model5GsUserState `json:"userState,omitempty"`

	Var5gSrvccInfo Model5GSrvccInfo `json:"5gSrvccInfo,omitempty"`
}
