/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type MonitoringConfiguration struct {
	EventType EventType `json:"eventType"`

	ImmediateFlag bool `json:"immediateFlag,omitempty"`

	LocationReportingConfiguration LocationReportingConfiguration `json:"locationReportingConfiguration,omitempty"`

	AssociationType AssociationType `json:"associationType,omitempty"`

	DatalinkReportCfg DatalinkReportingConfiguration `json:"datalinkReportCfg,omitempty"`

	LossConnectivityCfg LossConnectivityCfg `json:"lossConnectivityCfg,omitempty"`

	// indicating a time in seconds.
	MaximumLatency int32 `json:"maximumLatency,omitempty"`

	// indicating a time in seconds.
	MaximumResponseTime int32 `json:"maximumResponseTime,omitempty"`

	SuggestedPacketNumDl int32 `json:"suggestedPacketNumDl,omitempty"`

	PduSessionStatusCfg PduSessionStatusCfg `json:"pduSessionStatusCfg,omitempty"`

	ReachabilityForSmsCfg ReachabilityForSmsConfiguration `json:"reachabilityForSmsCfg,omitempty"`

	// String uniquely identifying MTC provider information.
	MtcProviderInformation string `json:"mtcProviderInformation,omitempty"`

	AfId string `json:"afId,omitempty"`

	ReachabilityForDataCfg ReachabilityForDataConfiguration `json:"reachabilityForDataCfg,omitempty"`

	IdleStatusInd bool `json:"idleStatusInd,omitempty"`
}
