/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"time"
)

// TrafficInfluDataPatch - Represents the Traffic Influence Data to be updated in the UDR.
type TrafficInfluDataPatch struct {

	// Contains the Notification Correlation Id allocated by the NEF for the UP path change notification. 
	UpPathChgNotifCorreId string `json:"upPathChgNotifCorreId,omitempty"`

	// Identifies whether an application can be relocated once a location of the application has been selected.
	AppReloInd bool `json:"appReloInd,omitempty"`

	// Identifies Ethernet packet filters. Either \"trafficFilters\" or \"ethTrafficFilters\" shall be included if applicable. 
	EthTrafficFilters []EthFlowDescription `json:"ethTrafficFilters,omitempty"`

	// Identifies IP packet filters. Either \"trafficFilters\" or \"ethTrafficFilters\" shall be included if applicable. 
	TrafficFilters []FlowInfo `json:"trafficFilters,omitempty"`

	// Identifies the N6 traffic routing requirement.
	TrafficRoutes []RouteToLocation `json:"trafficRoutes,omitempty"`

	TraffCorreInd bool `json:"traffCorreInd,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidStartTime time.Time `json:"validStartTime,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidEndTime time.Time `json:"validEndTime,omitempty"`

	// Identifies the temporal validities for the N6 traffic routing requirement.
	TempValidities *[]TemporalValidity `json:"tempValidities,omitempty"`

	NwAreaInfo NetworkAreaInfo2 `json:"nwAreaInfo,omitempty"`

	// String providing an URI formatted according to RFC 3986
	UpPathChgNotifUri string `json:"upPathChgNotifUri,omitempty"`

	Headers []string `json:"headers,omitempty"`

	AfAckInd bool `json:"afAckInd,omitempty"`

	AddrPreserInd bool `json:"addrPreserInd,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible with the OpenAPI 'nullable: true' property.
	MaxAllowedUpLat *int32 `json:"maxAllowedUpLat,omitempty"`

	// Indicates whether simultaneous connectivity should be temporarily maintained for the source and target PSA. 
	SimConnInd bool `json:"simConnInd,omitempty"`

	// indicating a time in seconds with OpenAPI defined 'nullable: true' property.
	SimConnTerm *int32 `json:"simConnTerm,omitempty"`
}
