/*
 * Namf_MBSBroadcast
 *
 * AMF MBSBroadcast Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ContextCreateReqData - Data within ContextCreate Request
type ContextCreateReqData struct {

	MbsSessionId MbsSessionId `json:"mbsSessionId"`

	// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer.
	AreaSessionId int32 `json:"areaSessionId,omitempty"`

	MbsServiceArea MbsServiceArea `json:"mbsServiceArea"`

	N2MbsSmInfo N2MbsSmInfo `json:"n2MbsSmInfo,omitempty"`

	// String providing an URI formatted according to RFC 3986
	NotifyUri string `json:"notifyUri"`

	// indicating a time in seconds.
	MaxResponseTime int32 `json:"maxResponseTime,omitempty"`
}
