/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// WirelineServiceAreaRestriction1 - The \"restrictionType\" attribute and the \"areas\" attribute shall be either both present or absent. The empty array of areas is used when service is allowed/restricted nowhere.
type WirelineServiceAreaRestriction1 struct {
	RestrictionType RestrictionType `json:"restrictionType,omitempty"`

	Areas []WirelineArea1 `json:"areas,omitempty"`
}
