/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type NetLocAccessSupportAnyOf string

// List of NetLocAccessSupportAnyOf
const (
	ANR_NOT_SUPPORTED NetLocAccessSupportAnyOf = "ANR_NOT_SUPPORTED"
	TZR_NOT_SUPPORTED NetLocAccessSupportAnyOf = "TZR_NOT_SUPPORTED"
	LOC_NOT_SUPPORTED NetLocAccessSupportAnyOf = "LOC_NOT_SUPPORTED"
)
