/*
 * Naf_EventExposure
 *
 * AF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// CollectiveBehaviourFilter - Contains the collective behaviour filter information to be collected from UE.
type CollectiveBehaviourFilter struct {

	Type CollectiveBehaviourFilterType `json:"type"`

	// Value of the parameter type as in the type attribute.
	Value string `json:"value"`

	// Indicates whether request list of UE IDs that fulfill a collective behaviour within the area of interest. This attribute shall set to \"true\" if request the list of UE IDs, otherwise, set to \"false\". May only be present and sets to \"true\" if \"AfEvent\" sets to \"COLLECTIVE_BEHAVIOUR\". 
	ListOfUeInd bool `json:"listOfUeInd,omitempty"`
}
