/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ServingNfIdentity - Contains the serving Network Function identity.
type ServingNfIdentity struct {

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	ServNfInstId string `json:"servNfInstId,omitempty"`

	Guami Guami `json:"guami,omitempty"`

	AnGwAddr AnGwAddress `json:"anGwAddr,omitempty"`

	SgsnAddr SgsnAddress `json:"sgsnAddr,omitempty"`
}
