/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type SatelliteBackhaulCategoryAnyOf string

// List of SatelliteBackhaulCategoryAnyOf
const (
	GEO SatelliteBackhaulCategoryAnyOf = "GEO"
	MEO SatelliteBackhaulCategoryAnyOf = "MEO"
	LEO SatelliteBackhaulCategoryAnyOf = "LEO"
	OTHER_SAT SatelliteBackhaulCategoryAnyOf = "OTHER_SAT"
	NON_SATELLITE SatelliteBackhaulCategoryAnyOf = "NON_SATELLITE"
)
