/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type NotificationCauseAnyOf string

// List of NotificationCauseAnyOf
const (
	QOS_FULFILLED NotificationCauseAnyOf = "QOS_FULFILLED"
	QOS_NOT_FULFILLED NotificationCauseAnyOf = "QOS_NOT_FULFILLED"
	UP_SEC_FULFILLED NotificationCauseAnyOf = "UP_SEC_FULFILLED"
	UP_SEC_NOT_FULFILLED NotificationCauseAnyOf = "UP_SEC_NOT_FULFILLED"
)
