/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type EpsInterworkingIndicationAnyOf string

// List of EpsInterworkingIndicationAnyOf
const (
	NONE EpsInterworkingIndicationAnyOf = "NONE"
	WITH_N26 EpsInterworkingIndicationAnyOf = "WITH_N26"
	WITHOUT_N26 EpsInterworkingIndicationAnyOf = "WITHOUT_N26"
	IWK_NON_3_GPP EpsInterworkingIndicationAnyOf = "IWK_NON_3GPP"
)
