/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"time"
)

// VsmfUpdateError - Error within Update Response from V-SMF, or from I-SMF to SMF
type VsmfUpdateError struct {

	Error ExtProblemDetails `json:"error"`

	// Procedure Transaction Identifier
	Pti int32 `json:"pti,omitempty"`

	N1smCause string `json:"n1smCause,omitempty"`

	N1SmInfoFromUe RefToBinaryData `json:"n1SmInfoFromUe,omitempty"`

	UnknownN1SmInfo RefToBinaryData `json:"unknownN1SmInfo,omitempty"`

	FailedToAssignEbiList []Arp `json:"failedToAssignEbiList,omitempty"`

	NgApCause NgApCause `json:"ngApCause,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Var5gMmCauseValue int32 `json:"5gMmCauseValue,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	RecoveryTime time.Time `json:"recoveryTime,omitempty"`

	N4Info N4Information `json:"n4Info,omitempty"`

	N4InfoExt1 N4Information `json:"n4InfoExt1,omitempty"`

	N4InfoExt2 N4Information `json:"n4InfoExt2,omitempty"`

	N4InfoExt3 N4Information `json:"n4InfoExt3,omitempty"`
}
