/*
 * Npcf_AMPolicyAuthorization Service API
 *
 * PCF Access and Mobility Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AmTerminationCause - It represents the cause values that the PCF should report when requesting to an NF service consumer the deletion of an \"AF application AM context\" resource.
type AmTerminationCause struct {
}
