/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// DownlinkDataNotificationControlRm - This data type is defined in the same way as the DownlinkDataNotificationControl data type, but with the nullable:true property.
type DownlinkDataNotificationControlRm struct {
	NotifCtrlInds *[]NotificationControlIndication `json:"notifCtrlInds,omitempty"`

	TypesOfNotif *[]DlDataDeliveryStatus `json:"typesOfNotif,omitempty"`
}
