/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ScpDomainRoutingInformation - SCP Domain Routing Information
type ScpDomainRoutingInformation struct {

	// This IE shall contain map of SCP domain interconnection information, where the key of the map is a SCP domain. The value of each entry shall be the interconnectivity information of the the SCP domain indicated by the key.  An empty map indicates that there is no SCP domain currently registered in the NRF. 
	ScpDomainList map[string]ScpDomainConnectivity `json:"scpDomainList"`
}
