/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ServiceIdentification - Identifies the service to which the subscription applies.
type ServiceIdentification struct {
	ServEthFlows []EthernetFlowInfo `json:"servEthFlows,omitempty"`

	ServIpFlows []IpFlowInfo `json:"servIpFlows,omitempty"`

	// Contains an AF application identifier.
	AfAppId string `json:"afAppId,omitempty"`
}
