/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// NfServiceSetCond - Subscription to a set of NFs based on their Service Set Id
type NfServiceSetCond struct {

	// NF Service Set Identifier (see clause 28.12 of 3GPP TS 23.003) formatted as the following  string  \" set<Set ID>.sn<Service Name>.nfi<NF Instance ID>.5gc.mnc<MNC>.mcc<MCC>\">\", or  \"set<SetID>.sn<ServiceName>.nfi<NFInstanceID>.5gc.nid<NID>.mnc<MNC>.mcc<MCC>\" with <MCC>  encoded as defined in clause 5.4.2 (\"Mcc\" data type definition)  <MNC> encoded as defined in  clause 5.4.2 (\"Mnc\" data type definition)  <NID> encoded as defined in clause 5.4.2 (\"Nid\"  data type definition) <NFInstanceId> encoded as defined in clause 5.3.2 <ServiceName> encoded  as defined in 3GPP TS 29.510 <Set ID> encoded as a string of characters consisting of  alphabetic characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that shall end  with either an alphabetic character or a digit.
	NfServiceSetId string `json:"nfServiceSetId"`

	// NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted as the following string \"  set<Set ID>.<nftype>set.5gc.mnc<MNC>.mcc<MCC>\", or \"set<SetID>.  <NFType>set.5gc.nid<NID>.mnc<MNC>.mcc<MCC>\" with <MCC> encoded as defined in clause 5.4.2  (\"Mcc\" data type definition) <MNC> encoded as defined in clause 5.4.2 (\"Mnc\" data type  definition) <NFType> encoded as a value defined in Table 6.1.6.3.3-1 of 3GPP TS 29.510 but  with lower case characters <Set ID> encoded as a string of characters consisting of alphabetic  characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that shall end with either an  alphabetic character or a digit.
	NfSetId string `json:"nfSetId,omitempty"`
}
