/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AuthorizationData - NIDD Authorization Information
type AuthorizationData struct {
	AuthorizationData []UserIdentifier `json:"authorizationData"`

	AllowedDnnList []AccessAndMobilitySubscriptionDataSubscribedDnnListInner `json:"allowedDnnList,omitempty"`

	AllowedSnssaiList []Snssai `json:"allowedSnssaiList,omitempty"`

	AllowedMtcProviders []MtcProvider `json:"allowedMtcProviders,omitempty"`
}
