/*
 * Npcf_UEPolicyControl
 *
 * UE Policy Control Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ProSeCapability - Possible values are: - PROSE_DD: This value is used to indicate that 5G ProSe Direct Discovery is supported   by the UE. - PROSE_DC: This value is used to indicate that 5G ProSe Direct Communication is supported   by the UE. - PROSE_L2_U2N_RELAY: This value is used to indicate that Layer-2 5G ProSe UE-to-Network   Relay is supported by the UE. - PROSE_L3_U2N_RELAY: This value is used to indicate that Layer-3 5G ProSe UE-to-Network   Relay is supported by the UE. - PROSE_L2_REMOTE_UE: This value is used to indicate that Layer-2 5G ProSe Remote UE is   supported by the UE. - PROSE_L3_REMOTE_UE: This value is used to indicate that Layer-3 5G ProSe Remote UE is   supported by the UE.
type ProSeCapability struct {
}
