/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"time"
)

// SmPolicyDecision - Contains the SM policies authorized by the PCF.
type SmPolicyDecision struct {

	// A map of Sessionrules with the content being the SessionRule as described in clause 5.6.2.7. The key used in this map for each entry is the sessRuleId attribute of the corresponding SessionRule.
	SessRules map[string]SessionRule `json:"sessRules,omitempty"`

	// A map of PCC rules with the content being the PCCRule as described in  clause 5.6.2.6. The key used in this map for each entry is the pccRuleId attribute of the corresponding PccRule.
	PccRules *map[string]PccRule `json:"pccRules,omitempty"`

	// If it is included and set to true, it indicates the P-CSCF Restoration is requested.
	PcscfRestIndication bool `json:"pcscfRestIndication,omitempty"`

	// Map of QoS data policy decisions. The key used in this map for each entry is the qosId attribute of the corresponding QosData.
	QosDecs map[string]QosData `json:"qosDecs,omitempty"`

	// Map of Charging data policy decisions. The key used in this map for each entry is the chgId attribute of the corresponding ChargingData.
	ChgDecs *map[string]ChargingData `json:"chgDecs,omitempty"`

	ChargingInfo ChargingInformation `json:"chargingInfo,omitempty"`

	// Map of Traffic Control data policy decisions. The key used in this map for each entry is the tcId attribute of the corresponding TrafficControlData.
	TraffContDecs map[string]TrafficControlData `json:"traffContDecs,omitempty"`

	// Map of Usage Monitoring data policy decisions. The key used in this map for each entry is the umId attribute of the corresponding UsageMonitoringData.
	UmDecs *map[string]UsageMonitoringData `json:"umDecs,omitempty"`

	// Map of QoS characteristics for non standard 5QIs. This map uses the 5QI values as keys.
	QosChars map[string]QosCharacteristics `json:"qosChars,omitempty"`

	// Map of QoS Monitoring data policy decisions. The key used in this map for each entry is the qmId attribute of the corresponding QosMonitoringData.
	QosMonDecs *map[string]QosMonitoringData `json:"qosMonDecs,omitempty"`

	// indicating a time in seconds.
	ReflectiveQoSTimer int32 `json:"reflectiveQoSTimer,omitempty"`

	// A map of condition data with the content being as described in clause 5.6.2.9. The key used in this map for each entry is the condId attribute of the corresponding ConditionData.
	Conds *map[string]ConditionData `json:"conds,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	RevalidationTime time.Time `json:"revalidationTime,omitempty"`

	// Indicates the offline charging is applicable to the PDU session when it is included and set to true.
	Offline bool `json:"offline,omitempty"`

	// Indicates the online charging is applicable to the PDU session when it is included and set to true.
	Online bool `json:"online,omitempty"`

	// Indicates that the online charging method shall never be used for any PCC rule activated during the lifetime of the PDU session.
	OfflineChOnly bool `json:"offlineChOnly,omitempty"`

	// Defines the policy control request triggers subscribed by the PCF.
	PolicyCtrlReqTriggers *[]PolicyControlRequestTrigger `json:"policyCtrlReqTriggers,omitempty"`

	// Defines the last list of rule control data requested by the PCF.
	LastReqRuleData []RequestedRuleData `json:"lastReqRuleData,omitempty"`

	LastReqUsageData RequestedUsageData `json:"lastReqUsageData,omitempty"`

	// Map of PRA information. The praId attribute within the PresenceInfo data type is the key of the map.
	PraInfos *map[string]PresenceInfoRm `json:"praInfos,omitempty"`

	// Represents information that identifies which IP pool or external server is used to allocate the IP address.
	Ipv4Index int32 `json:"ipv4Index,omitempty"`

	// Represents information that identifies which IP pool or external server is used to allocate the IP address.
	Ipv6Index int32 `json:"ipv6Index,omitempty"`

	QosFlowUsage QosFlowUsage `json:"qosFlowUsage,omitempty"`

	RelCause SmPolicyAssociationReleaseCause `json:"relCause,omitempty"`

	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
	SuppFeat string `json:"suppFeat,omitempty"`

	TsnBridgeManCont BridgeManagementContainer `json:"tsnBridgeManCont,omitempty"`

	TsnPortManContDstt PortManagementContainer `json:"tsnPortManContDstt,omitempty"`

	TsnPortManContNwtts []PortManagementContainer `json:"tsnPortManContNwtts,omitempty"`

	// Indicates whether the PDU session is a redundant PDU session. If absent it means the PDU session is not a redundant PDU session.
	RedSessIndication bool `json:"redSessIndication,omitempty"`
}
