/*
 * Nsmsf_SMService Service API
 *
 * SMSF SMService.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type RatTypeAnyOf string

// List of RatTypeAnyOf
const (
	VIRTUAL RatTypeAnyOf = "VIRTUAL"
	NBIOT RatTypeAnyOf = "NBIOT"
	WIRELINE RatTypeAnyOf = "WIRELINE"
	WIRELINE_CABLE RatTypeAnyOf = "WIRELINE_CABLE"
	WIRELINE_BBF RatTypeAnyOf = "WIRELINE_BBF"
	LTE_M RatTypeAnyOf = "LTE-M"
	NR_U RatTypeAnyOf = "NR_U"
	EUTRA_U RatTypeAnyOf = "EUTRA_U"
	TRUSTED_N3_GA RatTypeAnyOf = "TRUSTED_N3GA"
	TRUSTED_WLAN RatTypeAnyOf = "TRUSTED_WLAN"
	UTRA RatTypeAnyOf = "UTRA"
	GERA RatTypeAnyOf = "GERA"
	NR_LEO RatTypeAnyOf = "NR_LEO"
	NR_MEO RatTypeAnyOf = "NR_MEO"
	NR_GEO RatTypeAnyOf = "NR_GEO"
	NR_OTHER_SAT RatTypeAnyOf = "NR_OTHER_SAT"
	NR_REDCAP RatTypeAnyOf = "NR_REDCAP"
)
