/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// CnAssistedRanPara - SMF derived CN assisted RAN parameters tuning
type CnAssistedRanPara struct {

	StationaryIndication StationaryIndication `json:"stationaryIndication,omitempty"`

	// indicating a time in seconds.
	CommunicationDurationTime int32 `json:"communicationDurationTime,omitempty"`

	// indicating a time in seconds.
	PeriodicTime int32 `json:"periodicTime,omitempty"`

	ScheduledCommunicationTime ScheduledCommunicationTime `json:"scheduledCommunicationTime,omitempty"`

	ScheduledCommunicationType ScheduledCommunicationType `json:"scheduledCommunicationType,omitempty"`

	TrafficProfile TrafficProfile `json:"trafficProfile,omitempty"`

	BatteryIndication BatteryIndication `json:"batteryIndication,omitempty"`
}
