/*
 * Npcf_UEPolicyControl
 *
 * UE Policy Control Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// N2InfoContent - Represents a transparent N2 information content to be relayed by AMF
type N2InfoContent struct {

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	NgapMessageType int32 `json:"ngapMessageType,omitempty"`

	NgapIeType NgapIeType `json:"ngapIeType,omitempty"`

	NgapData RefToBinaryData `json:"ngapData"`
}
