/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type AccessStateTransitionTypeAnyOf string

// List of AccessStateTransitionTypeAnyOf
const (
	ACCESS_TYPE_CHANGE_3_GPP     AccessStateTransitionTypeAnyOf = "ACCESS_TYPE_CHANGE_3GPP"
	ACCESS_TYPE_CHANGE_N3_GPP    AccessStateTransitionTypeAnyOf = "ACCESS_TYPE_CHANGE_N3GPP"
	RM_STATE_CHANGE_DEREGISTERED AccessStateTransitionTypeAnyOf = "RM_STATE_CHANGE_DEREGISTERED"
	RM_STATE_CHANGE_REGISTERED   AccessStateTransitionTypeAnyOf = "RM_STATE_CHANGE_REGISTERED"
	CM_STATE_CHANGE_IDLE         AccessStateTransitionTypeAnyOf = "CM_STATE_CHANGE_IDLE"
	CM_STATE_CHANGE_CONNECTED    AccessStateTransitionTypeAnyOf = "CM_STATE_CHANGE_CONNECTED"
	HANDOVER                     AccessStateTransitionTypeAnyOf = "HANDOVER"
	MOBILITY_REGISTRATION_UPDATE AccessStateTransitionTypeAnyOf = "MOBILITY_REGISTRATION_UPDATE"
)
