/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type DataIndAnyOf string

// List of DataIndAnyOf
const (
	PFD       DataIndAnyOf = "PFD"
	IPTV      DataIndAnyOf = "IPTV"
	BDT       DataIndAnyOf = "BDT"
	SVC_PARAM DataIndAnyOf = "SVC_PARAM"
	AM        DataIndAnyOf = "AM"
)
