/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type PduSessionTypeAnyOf string

// List of PduSessionTypeAnyOf
const (
	IPV4         PduSessionTypeAnyOf = "IPV4"
	IPV6         PduSessionTypeAnyOf = "IPV6"
	IPV4_V6      PduSessionTypeAnyOf = "IPV4V6"
	UNSTRUCTURED PduSessionTypeAnyOf = "UNSTRUCTURED"
	ETHERNET     PduSessionTypeAnyOf = "ETHERNET"
)
