/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type FailureCauseAnyOf string

// List of FailureCauseAnyOf
const (
	PCC_RULE_EVENT FailureCauseAnyOf = "PCC_RULE_EVENT"
	PCC_QOS_FLOW_EVENT FailureCauseAnyOf = "PCC_QOS_FLOW_EVENT"
	RULE_PERMANENT_ERROR FailureCauseAnyOf = "RULE_PERMANENT_ERROR"
	RULE_TEMPORARY_ERROR FailureCauseAnyOf = "RULE_TEMPORARY_ERROR"
	POL_DEC_ERROR FailureCauseAnyOf = "POL_DEC_ERROR"
)
