/*
 * LMF Location
 *
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.4
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// UeConnectivityState - Indicates the connectivity state of a UE.
type UeConnectivityState struct {

	AccessType AccessType `json:"accessType"`

	Connectivitystate CmState `json:"connectivitystate,omitempty"`
}
