/*
 * Namf_MBSBroadcast
 *
 * AMF MBSBroadcast Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// Tmgi - Temporary Mobile Group Identity
type Tmgi struct {

	// MBS Service ID
	MbsServiceId string `json:"mbsServiceId"`

	PlmnId PlmnId `json:"plmnId"`
}
