/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"time"
)

type Amf3GppAccessRegistrationModification struct {

	Guami Guami `json:"guami"`

	PurgeFlag bool `json:"purgeFlag,omitempty"`

	// String representing a Permanent Equipment Identifier that may contain - an IMEI or IMEISV, as  specified in clause 6.2 of 3GPP TS 23.003; a MAC address for a 5G-RG or FN-RG via wireline  access, with an indication that this address cannot be trusted for regulatory purpose if this  address cannot be used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7  of 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345.  
	Pei string `json:"pei,omitempty"`

	ImsVoPs ImsVoPs `json:"imsVoPs,omitempty"`

	BackupAmfInfo []BackupAmfInfo `json:"backupAmfInfo,omitempty"`

	EpsInterworkingInfo EpsInterworkingInfo `json:"epsInterworkingInfo,omitempty"`

	UeSrvccCapability *bool `json:"ueSrvccCapability,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	RegistrationTime time.Time `json:"registrationTime,omitempty"`
}
