/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type LocationFilterAnyOf string

// List of LocationFilterAnyOf
const (
	TAI      LocationFilterAnyOf = "TAI"
	CELL_ID  LocationFilterAnyOf = "CELL_ID"
	RAN_NODE LocationFilterAnyOf = "RAN_NODE"
	UDP_PORT LocationFilterAnyOf = "UDP_PORT"
	TNAP_ID  LocationFilterAnyOf = "TNAP_ID"
	GLI      LocationFilterAnyOf = "GLI"
	TWAP_ID  LocationFilterAnyOf = "TWAP_ID"
)
