/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// SteeringInfo - Contains a combination of one PLMN identity and zero or more access technologies.
type SteeringInfo struct {
	PlmnId PlmnId1 `json:"plmnId"`

	AccessTechList []AccessTech `json:"accessTechList,omitempty"`
}
