/*
 * Naf_EventExposure
 *
 * AF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// ServiceExperienceInfoPerApp - Contains service experience information associated with an application.
type ServiceExperienceInfoPerApp struct {

	// String providing an application identifier.
	AppId string `json:"appId,omitempty"`

	AppServerIns AddrFqdn `json:"appServerIns,omitempty"`

	SvcExpPerFlows []ServiceExperienceInfoPerFlow `json:"svcExpPerFlows"`

	Gpsis []string `json:"gpsis,omitempty"`

	Supis []string `json:"supis,omitempty"`
}
