/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// TerminationInfo - Indicates the cause for requesting the deletion of the Individual Application Session Context resource.
type TerminationInfo struct {
	TermCause TerminationCause `json:"termCause"`

	// String providing an URI formatted according to RFC 3986
	ResUri string `json:"resUri"`
}
