/*
 * Nudm_UEAU
 *
 * UDM UE Authentication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.4
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type AvTypeAnyOf string

// List of AvTypeAnyOf
const (
	_5_G_HE_AKA AvTypeAnyOf = "5G_HE_AKA"
)
