/*
 * Npcf_AMPolicyAuthorization Service API
 *
 * PCF Access and Mobility Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AmTerminationInfo - Includes information related to the termination of the Individual Application AM Context resource.
type AmTerminationInfo struct {

	// Contains the Individual application AM context resource identifier related to the termination notification.
	AppAmContextId string `json:"appAmContextId"`

	TermCause AmTerminationCause `json:"termCause"`
}
