/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"time"
)

// MmTransactionLocationReportItem - UE MM Transaction Report Item per Location
type MmTransactionLocationReportItem struct {

	Tai Tai `json:"tai,omitempty"`

	Ncgi Ncgi `json:"ncgi,omitempty"`

	Ecgi Ecgi `json:"ecgi,omitempty"`

	N3gaLocation N3gaLocation `json:"n3gaLocation,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	Timestamp time.Time `json:"timestamp"`

	Transactions int32 `json:"transactions"`
}
