/*
 * Npcf_EventExposure
 *
 * PCF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// PcEventExposureSubsc - Represents an Individual Policy Events Subscription resource.
type PcEventExposureSubsc struct {

	EventSubs []PcEvent `json:"eventSubs"`

	EventsRepInfo ReportingInformation `json:"eventsRepInfo,omitempty"`

	// String identifying a group of devices network internal globally unique ID which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS 23.003.
	GroupId string `json:"groupId,omitempty"`

	FilterDnns []string `json:"filterDnns,omitempty"`

	FilterSnssais []Snssai `json:"filterSnssais,omitempty"`

	SnssaiDnns []SnssaiDnnCombination `json:"snssaiDnns,omitempty"`

	FilterServices []ServiceIdentification `json:"filterServices,omitempty"`

	// String providing an URI formatted according to RFC 3986
	NotifUri string `json:"notifUri"`

	NotifId string `json:"notifId"`

	EventNotifs []PcEventNotification `json:"eventNotifs,omitempty"`

	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
	SuppFeat string `json:"suppFeat,omitempty"`
}
