/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// NotifCondition - Condition (list of attributes in the NF Profile) to determine whether a notification must be sent by NRF
type NotifCondition struct {

	MonitoredAttributes []string `json:"monitoredAttributes,omitempty"`

	UnmonitoredAttributes []string `json:"unmonitoredAttributes,omitempty"`
}
