/*
 * LMF Location
 *
 * LMF Location Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.4
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type ResponseTimeAnyOf string

// List of ResponseTimeAnyOf
const (
	LOW_DELAY ResponseTimeAnyOf = "LOW_DELAY"
	DELAY_TOLERANT ResponseTimeAnyOf = "DELAY_TOLERANT"
	NO_DELAY ResponseTimeAnyOf = "NO_DELAY"
)
