/*
 * Namf_MBSBroadcast
 *
 * AMF MBSBroadcast Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0-alpha.2
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"os"
)

type ContextCreate201Response struct {

	JsonData ContextCreateRspData `json:"jsonData,omitempty"`

	BinaryDataN2Information1 *os.File `json:"binaryDataN2Information1,omitempty"`

	BinaryDataN2Information2 *os.File `json:"binaryDataN2Information2,omitempty"`

	BinaryDataN2Information3 *os.File `json:"binaryDataN2Information3,omitempty"`

	BinaryDataN2Information4 *os.File `json:"binaryDataN2Information4,omitempty"`

	BinaryDataN2Information5 *os.File `json:"binaryDataN2Information5,omitempty"`

	BinaryDataN2Information6 *os.File `json:"binaryDataN2Information6,omitempty"`

	BinaryDataN2Information7 *os.File `json:"binaryDataN2Information7,omitempty"`

	BinaryDataN2Information8 *os.File `json:"binaryDataN2Information8,omitempty"`

	BinaryDataN2Information9 *os.File `json:"binaryDataN2Information9,omitempty"`

	BinaryDataN2Information10 *os.File `json:"binaryDataN2Information10,omitempty"`
}
