/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type LcsMoServiceClassAnyOf string

// List of LcsMoServiceClassAnyOf
const (
	BASIC_SELF_LOCATION LcsMoServiceClassAnyOf = "BASIC_SELF_LOCATION"
	AUTONOMOUS_SELF_LOCATION LcsMoServiceClassAnyOf = "AUTONOMOUS_SELF_LOCATION"
	TRANSFER_TO_THIRD_PARTY LcsMoServiceClassAnyOf = "TRANSFER_TO_THIRD_PARTY"
)
