/*
 * Naf_EventExposure
 *
 * AF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"time"
)

// PerformanceDataCollection - Contains Performance Data Analytics related information collection.
type PerformanceDataCollection struct {

	// String providing an application identifier.
	AppId string `json:"appId,omitempty"`

	UeIpAddr IpAddr `json:"ueIpAddr,omitempty"`

	IpTrafficFilter FlowInfo `json:"ipTrafficFilter,omitempty"`

	UeLoc LocationArea5G `json:"ueLoc,omitempty"`

	AppLocs []string `json:"appLocs,omitempty"`

	AsAddr AddrFqdn `json:"asAddr,omitempty"`

	PerfData PerformanceData `json:"perfData"`

	// string with format 'date-time' as defined in OpenAPI.
	TimeStamp time.Time `json:"timeStamp"`
}
