/*
 * Nsmsf_SMService Service API
 *
 * SMSF SMService.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type LineTypeAnyOf string

// List of LineTypeAnyOf
const (
	DSL LineTypeAnyOf = "DSL"
	PON LineTypeAnyOf = "PON"
)
