/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// TimePeriod - Contains the periodicity for the defined usage monitoring data limits.
type TimePeriod struct {
	Period Periodicity `json:"period"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MaxNumPeriod int32 `json:"maxNumPeriod,omitempty"`
}
