/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

import (
	"time"
)

type ExpectedUeBehaviour struct {
	AfInstanceId string `json:"afInstanceId"`

	ReferenceId int32 `json:"referenceId"`

	StationaryIndication StationaryIndicationRm `json:"stationaryIndication,omitempty"`

	// indicating a time in seconds with OpenAPI defined 'nullable: true' property.
	CommunicationDurationTime *int32 `json:"communicationDurationTime,omitempty"`

	ScheduledCommunicationType ScheduledCommunicationTypeRm `json:"scheduledCommunicationType,omitempty"`

	// indicating a time in seconds with OpenAPI defined 'nullable: true' property.
	PeriodicTime *int32 `json:"periodicTime,omitempty"`

	ScheduledCommunicationTime ScheduledCommunicationTimeRm `json:"scheduledCommunicationTime,omitempty"`

	// Identifies the UE's expected geographical movement. The attribute is only applicable in 5G.
	ExpectedUmts *[]LocationArea `json:"expectedUmts,omitempty"`

	TrafficProfile TrafficProfileRm `json:"trafficProfile,omitempty"`

	BatteryIndication BatteryIndicationRm `json:"batteryIndication,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime,omitempty"`

	// String uniquely identifying MTC provider information.
	MtcProviderInformation string `json:"mtcProviderInformation,omitempty"`
}
