/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type RequiredAccessInfoAnyOf string

// List of RequiredAccessInfoAnyOf
const (
	USER_LOCATION RequiredAccessInfoAnyOf = "USER_LOCATION"
	UE_TIME_ZONE  RequiredAccessInfoAnyOf = "UE_TIME_ZONE"
)
