/*
 * LMF Broadcast
 *
 * LMF Broadcast Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0-alpha.2
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type DataAvailabilityAnyOf string

// List of DataAvailabilityAnyOf
const (
	AVAILABLE DataAvailabilityAnyOf = "CIPHERING_KEY_DATA_AVAILABLE"
	NOT_AVAILABLE DataAvailabilityAnyOf = "CIPHERING_KEY_DATA_NOT_AVAILABLE"
)
