/*
 * LMF Broadcast
 *
 * LMF Broadcast Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0-alpha.2
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// CipheringKeyResponse - Information within Ciphering Key Data Notification Response.
type CipheringKeyResponse struct {

	CipheringDataReport []CipheringSetReport `json:"cipheringDataReport,omitempty"`
}
