/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// MlAnalyticsInfo - ML Analytics Filter information supported by the Nnwdaf_MLModelProvision service
type MlAnalyticsInfo struct {

	MlAnalyticsIds []NwdafEvent `json:"mlAnalyticsIds,omitempty"`

	SnssaiList []Snssai `json:"snssaiList,omitempty"`

	TrackingAreaList []Tai `json:"trackingAreaList,omitempty"`
}
