/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// PolicyDataChangeNotification - Contains changed policy data for which notification was requested.
type PolicyDataChangeNotification struct {

	AmPolicyData AmPolicyData `json:"amPolicyData,omitempty"`

	UePolicySet UePolicySet `json:"uePolicySet,omitempty"`

	PlmnUePolicySet UePolicySet `json:"plmnUePolicySet,omitempty"`

	SmPolicyData SmPolicyData `json:"smPolicyData,omitempty"`

	UsageMonData UsageMonData `json:"usageMonData,omitempty"`

	SponsorConnectivityData SponsorConnectivityData `json:"SponsorConnectivityData,omitempty"`

	BdtData BdtData `json:"bdtData,omitempty"`

	OpSpecData OperatorSpecificDataContainer `json:"opSpecData,omitempty"`

	// Operator Specific Data resource data, if changed and notification was requested. The key of the map is operator specific data element name and the value is the operator specific data of the UE. 
	OpSpecDataMap map[string]OperatorSpecificDataContainer `json:"opSpecDataMap,omitempty"`

	// String represents the SUPI or GPSI
	UeId string `json:"ueId,omitempty"`

	SponsorId string `json:"sponsorId,omitempty"`

	// string identifying a BDT Reference ID as defined in clause 5.3.3 of 3GPP TS 29.154.
	BdtRefId string `json:"bdtRefId,omitempty"`

	UsageMonId string `json:"usageMonId,omitempty"`

	PlmnId PlmnId1 `json:"plmnId,omitempty"`

	DelResources []string `json:"delResources,omitempty"`

	NotifId string `json:"notifId,omitempty"`

	ReportedFragments []NotificationItem `json:"reportedFragments,omitempty"`

	SlicePolicyData SlicePolicyData `json:"slicePolicyData,omitempty"`

	Snssai Snssai `json:"snssai,omitempty"`
}
