/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// NotificationItem - Identifies a data change notification when the change occurs in a fragment (subset of resource data) of a given resource.
type NotificationItem struct {

	// String providing an URI formatted according to RFC 3986
	ResourceId string `json:"resourceId"`

	NotifItems []UpdatedItem `json:"notifItems"`
}
