/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// GroupIdentifiers - External or Internal Group Identifier with a list of group members
type GroupIdentifiers struct {

	ExtGroupId string `json:"extGroupId,omitempty"`

	// String identifying a group of devices network internal globally unique ID which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS 23.003.
	IntGroupId string `json:"intGroupId,omitempty"`

	UeIdList []UeId `json:"ueIdList,omitempty"`

	AllowedAfIds []string `json:"allowedAfIds,omitempty"`
}
