/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// NwdafRegistrationInfo - List of NwdafRegistration
type NwdafRegistrationInfo struct {

	NwdafRegistrationList []NwdafRegistration `json:"nwdafRegistrationList"`
}
