/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// RetrieveData - Data within Retrieve Request
type RetrieveData struct {

	SmallDataRateStatusReq bool `json:"smallDataRateStatusReq,omitempty"`

	PduSessionContextType PduSessionContextType `json:"pduSessionContextType,omitempty"`
}
