/*
 * Nudm_UEAU
 *
 * UDM UE Authentication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.4
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

type GbaAuthTypeAnyOf string

// List of GbaAuthTypeAnyOf
const (
	DIGEST_AKAV1_MD5 GbaAuthTypeAnyOf = "DIGEST_AKAV1_MD5"
)
