/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// EasIpReplacementInfo - Contains EAS IP replacement information for a Source and a Target EAS.
type EasIpReplacementInfo struct {

	Source EasServerAddress `json:"source"`

	Target EasServerAddress `json:"target"`
}
