/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// NwdafData - Indicates the list of Analytic ID(s) per NWDAF instance ID used for the PDU Session consumed by the SMF.
type NwdafData struct {

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
	NwdafInstanceId string `json:"nwdafInstanceId"`

	NwdafEvents []NwdafEvent `json:"nwdafEvents,omitempty"`
}
