/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.5
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// N4Information - N4 Information
type N4Information struct {

	N4MessageType N4MessageType `json:"n4MessageType"`

	N4MessagePayload RefToBinaryData `json:"n4MessagePayload"`

	N4DnaiInfo DnaiInformation `json:"n4DnaiInfo,omitempty"`

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	PsaUpfId string `json:"psaUpfId,omitempty"`
}
