/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// PcfUeCallbackInfo - Contains the PCF for the UE information necessary for the PCF for the PDU session to send  SM Policy Association Establishment and Termination events. 
type PcfUeCallbackInfo struct {

	// String providing an URI formatted according to RFC 3986
	CallbackUri string `json:"callbackUri"`

	BindingInfo string `json:"bindingInfo,omitempty"`
}
