/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// AuthenticationSubscription - A UE's authentication data.
type AuthenticationSubscription struct {

	AuthenticationMethod AuthMethod `json:"authenticationMethod"`

	EncPermanentKey string `json:"encPermanentKey,omitempty"`

	ProtectionParameterId string `json:"protectionParameterId,omitempty"`

	SequenceNumber SequenceNumber `json:"sequenceNumber,omitempty"`

	AuthenticationManagementField string `json:"authenticationManagementField,omitempty"`

	AlgorithmId string `json:"algorithmId,omitempty"`

	EncOpcKey string `json:"encOpcKey,omitempty"`

	EncTopcKey string `json:"encTopcKey,omitempty"`

	VectorGenerationInHss bool `json:"vectorGenerationInHss,omitempty"`

	// Identifier of a group of NFs.
	HssGroupId string `json:"hssGroupId,omitempty"`

	N5gcAuthMethod AuthMethod `json:"n5gcAuthMethod,omitempty"`

	RgAuthenticationInd bool `json:"rgAuthenticationInd,omitempty"`

	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause 2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2 of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2 of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of 3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall only contain characters allowed according to the \"lower-with-hyphen\" naming convention defined in 3GPP TS 29.501. 
	Supi string `json:"supi,omitempty"`

	AkmaAllowed bool `json:"akmaAllowed,omitempty"`

	RoutingId string `json:"routingId,omitempty"`
}
