/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// SmPolicyNotification - Represents a notification on the update of the SM policies.
type SmPolicyNotification struct {

	// String providing an URI formatted according to RFC 3986
	ResourceUri string `json:"resourceUri,omitempty"`

	SmPolicyDecision SmPolicyDecision `json:"smPolicyDecision,omitempty"`
}
