/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://model-generator.tech)
 */

package model

// EasdfInfo - Information of an EASDF NF Instance
type EasdfInfo struct {

	SNssaiEasdfInfoList []SnssaiEasdfInfoItem `json:"sNssaiEasdfInfoList,omitempty"`

	EasdfN6IpAddressList []IpAddr `json:"easdfN6IpAddressList,omitempty"`

	UpfN6IpAddressList []IpAddr `json:"upfN6IpAddressList,omitempty"`
}
