/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handler

import (
	"gogc/src/common/logger"
	"gogc/src/model"
	"gogc/src/udm/SubscriberDataManagement/scenario"
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetNSSAI - retrieve a UE's subscribed NSSAI
func GetNSSAI(c *gin.Context) {

	logger.Debug("GetNSSAI START")
	defer logger.Debug("GetNSSAI END")

	// Get Parameter
	request := model.Request{}
	request.Params["supi"] = c.Param("supi")
	request.Query = c.Request.URL.Query()

	// Call Scenario Function
	response, err := scenario.GetNSSAI(request)
	// logger.Debug("response:%#+v, err:%v", response, err)

	if err == nil {
		c.JSON(http.StatusOK, response)
	} else {
		c.JSON(http.StatusNotFound, response)
	}
}
