/*
 * Namf_MT
 *
 * AMF Mobile Terminated Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// EnableUeReachability - Namf_MT EnableUEReachability service Operation
func EnableUeReachability(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
