/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetNon3GppSmsfRegistration - retrieve the SMSF registration for non-3GPP access information
func GetNon3GppSmsfRegistration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
