/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/nudm-uecm/v1/",
		Index,
	},

	{
		"Get3GppRegistration",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations/amf-3gpp-access",
		Get3GppRegistration,
	},

	{
		"GetNon3GppRegistration",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations/amf-non-3gpp-access",
		GetNon3GppRegistration,
	},

	{
		"Call3GppRegistration",
		http.MethodPut,
		"/nudm-uecm/v1/:ueId/registrations/amf-3gpp-access",
		Call3GppRegistration,
	},

	{
		"Non3GppRegistration",
		http.MethodPut,
		"/nudm-uecm/v1/:ueId/registrations/amf-non-3gpp-access",
		Non3GppRegistration,
	},

	{
		"IpSmGwDeregistration",
		http.MethodDelete,
		"/nudm-uecm/v1/:ueId/registrations/ip-sm-gw",
		IpSmGwDeregistration,
	},

	{
		"IpSmGwRegistration",
		http.MethodPut,
		"/nudm-uecm/v1/:ueId/registrations/ip-sm-gw",
		IpSmGwRegistration,
	},

	{
		"GetIpSmGwRegistration",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations/ip-sm-gw",
		GetIpSmGwRegistration,
	},

	{
		"NwdafDeregistration",
		http.MethodDelete,
		"/nudm-uecm/v1/:ueId/registrations/nwdaf-registrations/:nwdafRegistrationId",
		NwdafDeregistration,
	},

	{
		"NwdafRegistration",
		http.MethodPut,
		"/nudm-uecm/v1/:ueId/registrations/nwdaf-registrations/:nwdafRegistrationId",
		NwdafRegistration,
	},

	{
		"GetNwdafRegistration",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations/nwdaf-registrations",
		GetNwdafRegistration,
	},

	{
		"PeiUpdate",
		http.MethodPost,
		"/nudm-uecm/v1/:ueId/registrations/amf-3gpp-access/pei-update",
		PeiUpdate,
	},

	{
		"Update3GppRegistration",
		http.MethodPatch,
		"/nudm-uecm/v1/:ueId/registrations/amf-3gpp-access",
		Update3GppRegistration,
	},

	{
		"UpdateNon3GppRegistration",
		http.MethodPatch,
		"/nudm-uecm/v1/:ueId/registrations/amf-non-3gpp-access",
		UpdateNon3GppRegistration,
	},

	{
		"UpdateNwdafRegistration",
		http.MethodPatch,
		"/nudm-uecm/v1/:ueId/registrations/nwdaf-registrations/:nwdafRegistrationId",
		UpdateNwdafRegistration,
	},

	{
		"UpdateSmfRegistration",
		http.MethodPatch,
		"/nudm-uecm/v1/:ueId/registrations/smf-registrations/:pduSessionId",
		UpdateSmfRegistration,
	},

	{
		"RetrieveSmfRegistration",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations/smf-registrations/:pduSessionId",
		RetrieveSmfRegistration,
	},

	{
		"UpdateRoamingInformation",
		http.MethodPost,
		"/nudm-uecm/v1/:ueId/registrations/amf-3gpp-access/roaming-info-update",
		UpdateRoamingInformation,
	},

	{
		"SmfDeregistration",
		http.MethodDelete,
		"/nudm-uecm/v1/:ueId/registrations/smf-registrations/:pduSessionId",
		SmfDeregistration,
	},

	{
		"GetSmfRegistration",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations/smf-registrations",
		GetSmfRegistration,
	},

	{
		"Registration",
		http.MethodPut,
		"/nudm-uecm/v1/:ueId/registrations/smf-registrations/:pduSessionId",
		Registration,
	},

	{
		"Get3GppSmsfRegistration",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations/smsf-3gpp-access",
		Get3GppSmsfRegistration,
	},

	{
		"Call3GppSmsfDeregistration",
		http.MethodDelete,
		"/nudm-uecm/v1/:ueId/registrations/smsf-3gpp-access",
		Call3GppSmsfDeregistration,
	},

	{
		"Non3GppSmsfDeregistration",
		http.MethodDelete,
		"/nudm-uecm/v1/:ueId/registrations/smsf-non-3gpp-access",
		Non3GppSmsfDeregistration,
	},

	{
		"GetNon3GppSmsfRegistration",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations/smsf-non-3gpp-access",
		GetNon3GppSmsfRegistration,
	},

	{
		"Call3GppSmsfRegistration",
		http.MethodPut,
		"/nudm-uecm/v1/:ueId/registrations/smsf-3gpp-access",
		Call3GppSmsfRegistration,
	},

	{
		"Non3GppSmsfRegistration",
		http.MethodPut,
		"/nudm-uecm/v1/:ueId/registrations/smsf-non-3gpp-access",
		Non3GppSmsfRegistration,
	},

	{
		"DeregAMF",
		http.MethodPost,
		"/nudm-uecm/v1/:ueId/registrations/amf-3gpp-access/dereg-amf",
		DeregAMF,
	},

	{
		"TriggerPCSCFRestoration",
		http.MethodPost,
		"/nudm-uecm/v1/restore-pcscf",
		TriggerPCSCFRestoration,
	},

	{
		"GetRegistrations",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations",
		GetRegistrations,
	},

	{
		"GetLocationInfo",
		http.MethodGet,
		"/nudm-uecm/v1/:ueId/registrations/location",
		GetLocationInfo,
	},
}
