/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "gogc/src/udm/SubscriberDataManagement/handler"
	"gogc/src/udm/SubscriberDataManagement/scenario"
	"log"
	"os"
)

func main() {
	log.Printf("Server started")

	// Init
	scenario.Init()
	router := sw.NewRouter()

	port := os.Getenv("ENV_NRF_SUBSCRIBER_DATA_MANAGEMENT_PORT")
	if port == "" {
		port = "8380"
	}
	port = ":" + port

	log.Fatal(router.Run(port))
}
