/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "gogc/src/nrf/NFManagement/handler"
	"log"
	"os"
)

func main() {
	log.Printf("Server started")

	// Init
	router := sw.NewRouter()

	port := os.Getenv("ENV_NRF_NFMANAGEMENT_PORT")
	if port == "" {
		port = "8504"
	}
	port = ":" + port

	log.Fatal(router.Run(port))
}
