/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreatePPDataEntry - Create a Provisioning Parameter Data Entry
func CreatePPDataEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeletePPDataEntry - Delete a Provisioning Parameter Data Entry
func DeletePPDataEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPPDataEntry - get Parameter Provisioning Data Entry
func GetPPDataEntry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
