/*
 * Naf_EventExposure
 *
 * AF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteAfEventExposureSubsc - Cancels an existing Individual Application Event Subscription 
func DeleteAfEventExposureSubsc(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAfEventExposureSubsc - Reads an existing Individual Application Event Subscription
func GetAfEventExposureSubsc(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PutAfEventExposureSubsc - Modifies an existing Individual Application Event Subscription 
func PutAfEventExposureSubsc(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
