/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://handler-generator.tech)
 */

package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateOrReplaceSessionManagementData - Creates and updates the session management data for a UE and for an individual PDU session
func CreateOrReplaceSessionManagementData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteSessionManagementData - Deletes the session management data for a UE and for an individual PDU session
func DeleteSessionManagementData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// QuerySessionManagementData - Retrieves the session management data for a UE and for an individual PDU session
func QuerySessionManagementData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
