/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://handler-generator.tech)
 */

package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateSmsfContext3gpp - Create the SMSF context data of a UE via 3GPP access
func CreateSmsfContext3gpp(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteSmsfContext3gpp - To remove the SMSF context data of a UE via 3GPP access
func DeleteSmsfContext3gpp(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// QuerySmsfContext3gpp - Retrieves the SMSF context data of a UE using 3gpp access
func QuerySmsfContext3gpp(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
