/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateIndividualAppliedBdtPolicyData - Create an individual applied BDT Policy Data resource
func CreateIndividualAppliedBdtPolicyData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteIndividualAppliedBdtPolicyData - Delete an individual Applied BDT Policy Data resource
func DeleteIndividualAppliedBdtPolicyData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateIndividualAppliedBdtPolicyData - Modify part of the properties of an individual Applied BDT Policy Data resource
func UpdateIndividualAppliedBdtPolicyData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
