/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://handler-generator.tech)
 */

package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateAmfGroupSubscriptions - Create AmfSubscriptions for a group of UEs or any UE
func CreateAmfGroupSubscriptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ModifyAmfGroupSubscriptions - Modify AmfSubscriptions for a group of UEs or any UE
func ModifyAmfGroupSubscriptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
