/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://handler-generator.tech)
 */

package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateOrReplaceServiceParameterData - Create or update an individual Service Parameter Data resource
func CreateOrReplaceServiceParameterData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteIndividualServiceParameterData - Delete an individual Service Parameter Data resource
func DeleteIndividualServiceParameterData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateIndividualServiceParameterData - Modify part of the properties of an individual Service Parameter Data resource
func UpdateIndividualServiceParameterData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
