/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteOperatorSpecificData - When the feature OSDResource_Create_Delete is supported, delete OperatorSpecificData resource
func DeleteOperatorSpecificData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReadOperatorSpecificData - Retrieve the operator specific policy data of an UE
func ReadOperatorSpecificData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReplaceOperatorSpecificData - Create or modify the operator specific policy data of a UE
func ReplaceOperatorSpecificData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateOperatorSpecificData - Modify the operator specific policy data of a UE
func UpdateOperatorSpecificData(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
