/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.2.0-alpha.7
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ReadPlmnUePolicySet - Retrieve the UE policy set data for an H-PLMN
func ReadPlmnUePolicySet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
