/*
 * Npcf_UEPolicyControl
 *
 * UE Policy Control Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteIndividualUEPolicyAssociation - Delete individual UE policy association.
func DeleteIndividualUEPolicyAssociation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReadIndividualUEPolicyAssociation - Read individual UE policy association.
func ReadIndividualUEPolicyAssociation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReportObservedEventTriggersForIndividualUEPolicyAssociation - Report observed event triggers and possibly obtain updated policies for an individual UE policy association. 
func ReportObservedEventTriggersForIndividualUEPolicyAssociation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
