/*
 * 5G-EIR Equipment Identity Check
 *
 * 5G-EIR Equipment Identity Check Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.2.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"gogc/src/common/db"
	sw "gogc/src/station/handler"
	"log"
	"os"
)

func main() {
	log.Printf("Server started")

	// Init
	router := sw.NewRouter()
	db.Init()

	port := os.Getenv("ENV_DATABASE_PORT")
	if port == "" {
		port = "8888"
	}
	port = ":" + port

	log.Fatal(router.Run(port))
}
